#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 152
#define LARGE_STATE_COUNT 20
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 13

enum {
  sym_identifier = 1,
  sym_t_void = 2,
  sym_t_bool = 3,
  sym_t_int = 4,
  sym_t_float = 5,
  sym_t_str = 6,
  anon_sym_COLON = 7,
  anon_sym_COMMA = 8,
  anon_sym_fn = 9,
  anon_sym_DASH_GT = 10,
  anon_sym_pu = 11,
  anon_sym_EQ = 12,
  sym_int = 13,
  aux_sym_float_token1 = 14,
  aux_sym_float_token2 = 15,
  aux_sym_float_token3 = 16,
  sym_nil = 17,
  anon_sym_true = 18,
  anon_sym_false = 19,
  sym_str = 20,
  anon_sym_end = 21,
  anon_sym_do = 22,
  anon_sym_LPAREN = 23,
  anon_sym_RPAREN = 24,
  sym_source_file = 25,
  sym__type_primitive = 26,
  sym_parameter = 27,
  sym_parameters = 28,
  sym_t_fn = 29,
  sym_t_pu = 30,
  sym__type = 31,
  sym__inner_statement = 32,
  sym__outer_statement = 33,
  sym__declaration = 34,
  sym_const_declaration = 35,
  sym_mut_declaration = 36,
  sym_float = 37,
  sym_bool = 38,
  sym__fn_body = 39,
  sym_fn = 40,
  sym_pu = 41,
  sym__tup_params = 42,
  sym_fn_call = 43,
  sym_arrow_call = 44,
  sym_tup = 45,
  sym__expression = 46,
  aux_sym_source_file_repeat1 = 47,
  aux_sym_parameters_repeat1 = 48,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_t_void] = "t_void",
  [sym_t_bool] = "t_bool",
  [sym_t_int] = "t_int",
  [sym_t_float] = "t_float",
  [sym_t_str] = "t_str",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_fn] = "fn",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_pu] = "pu",
  [anon_sym_EQ] = "=",
  [sym_int] = "int",
  [aux_sym_float_token1] = "float_token1",
  [aux_sym_float_token2] = "float_token2",
  [aux_sym_float_token3] = "float_token3",
  [sym_nil] = "nil",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_str] = "str",
  [anon_sym_end] = "end",
  [anon_sym_do] = "do",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_source_file] = "source_file",
  [sym__type_primitive] = "_type_primitive",
  [sym_parameter] = "parameter",
  [sym_parameters] = "parameters",
  [sym_t_fn] = "t_fn",
  [sym_t_pu] = "t_pu",
  [sym__type] = "_type",
  [sym__inner_statement] = "_inner_statement",
  [sym__outer_statement] = "_outer_statement",
  [sym__declaration] = "_declaration",
  [sym_const_declaration] = "const_declaration",
  [sym_mut_declaration] = "mut_declaration",
  [sym_float] = "float",
  [sym_bool] = "bool",
  [sym__fn_body] = "_fn_body",
  [sym_fn] = "fn",
  [sym_pu] = "pu",
  [sym__tup_params] = "_tup_params",
  [sym_fn_call] = "fn_call",
  [sym_arrow_call] = "arrow_call",
  [sym_tup] = "tup",
  [sym__expression] = "_expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_t_void] = sym_t_void,
  [sym_t_bool] = sym_t_bool,
  [sym_t_int] = sym_t_int,
  [sym_t_float] = sym_t_float,
  [sym_t_str] = sym_t_str,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_pu] = anon_sym_pu,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_int] = sym_int,
  [aux_sym_float_token1] = aux_sym_float_token1,
  [aux_sym_float_token2] = aux_sym_float_token2,
  [aux_sym_float_token3] = aux_sym_float_token3,
  [sym_nil] = sym_nil,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_str] = sym_str,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_do] = anon_sym_do,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_source_file] = sym_source_file,
  [sym__type_primitive] = sym__type_primitive,
  [sym_parameter] = sym_parameter,
  [sym_parameters] = sym_parameters,
  [sym_t_fn] = sym_t_fn,
  [sym_t_pu] = sym_t_pu,
  [sym__type] = sym__type,
  [sym__inner_statement] = sym__inner_statement,
  [sym__outer_statement] = sym__outer_statement,
  [sym__declaration] = sym__declaration,
  [sym_const_declaration] = sym_const_declaration,
  [sym_mut_declaration] = sym_mut_declaration,
  [sym_float] = sym_float,
  [sym_bool] = sym_bool,
  [sym__fn_body] = sym__fn_body,
  [sym_fn] = sym_fn,
  [sym_pu] = sym_pu,
  [sym__tup_params] = sym__tup_params,
  [sym_fn_call] = sym_fn_call,
  [sym_arrow_call] = sym_arrow_call,
  [sym_tup] = sym_tup,
  [sym__expression] = sym__expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_t_void] = {
    .visible = true,
    .named = true,
  },
  [sym_t_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_t_int] = {
    .visible = true,
    .named = true,
  },
  [sym_t_float] = {
    .visible = true,
    .named = true,
  },
  [sym_t_str] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pu] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_float_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_float_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_float_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_nil] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_str] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__type_primitive] = {
    .visible = false,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_t_fn] = {
    .visible = true,
    .named = true,
  },
  [sym_t_pu] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym__inner_statement] = {
    .visible = false,
    .named = true,
  },
  [sym__outer_statement] = {
    .visible = false,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_const_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_mut_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym__fn_body] = {
    .visible = false,
    .named = true,
  },
  [sym_fn] = {
    .visible = true,
    .named = true,
  },
  [sym_pu] = {
    .visible = true,
    .named = true,
  },
  [sym__tup_params] = {
    .visible = false,
    .named = true,
  },
  [sym_fn_call] = {
    .visible = true,
    .named = true,
  },
  [sym_arrow_call] = {
    .visible = true,
    .named = true,
  },
  [sym_tup] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_body = 1,
  field_expression = 2,
  field_function = 3,
  field_name = 4,
  field_param1 = 5,
  field_parameters = 6,
  field_return = 7,
  field_type = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_expression] = "expression",
  [field_function] = "function",
  [field_name] = "name",
  [field_param1] = "param1",
  [field_parameters] = "parameters",
  [field_return] = "return",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 3},
  [7] = {.index = 9, .length = 3},
  [8] = {.index = 12, .length = 1},
  [9] = {.index = 13, .length = 1},
  [10] = {.index = 14, .length = 3},
  [11] = {.index = 17, .length = 3},
  [12] = {.index = 20, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_function, 0},
  [1] =
    {field_name, 0},
  [2] =
    {field_body, 2},
  [3] =
    {field_param1, 0},
  [4] =
    {field_expression, 3},
    {field_name, 0},
  [6] =
    {field_name, 0},
    {field_type, 1},
    {field_type, 2},
  [9] =
    {field_body, 3},
    {field_return, 1},
    {field_return, 2},
  [12] =
    {field_body, 3},
  [13] =
    {field_return, 2},
  [14] =
    {field_expression, 4},
    {field_name, 0},
    {field_type, 2},
  [17] =
    {field_body, 4},
    {field_return, 2},
    {field_return, 3},
  [20] =
    {field_parameters, 1},
    {field_return, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(35);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '(') ADVANCE(75);
      if (lookahead == ')') ADVANCE(76);
      if (lookahead == ',') ADVANCE(54);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == ':') ADVANCE(53);
      if (lookahead == '=') ADVANCE(60);
      if (lookahead == 'b') ADVANCE(22);
      if (lookahead == 'd') ADVANCE(18);
      if (lookahead == 'e') ADVANCE(16);
      if (lookahead == 'f') ADVANCE(5);
      if (lookahead == 'i') ADVANCE(17);
      if (lookahead == 'n') ADVANCE(12);
      if (lookahead == 'p') ADVANCE(29);
      if (lookahead == 's') ADVANCE(28);
      if (lookahead == 't') ADVANCE(24);
      if (lookahead == 'v') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(71);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == ',') ADVANCE(54);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == ':') ADVANCE(53);
      if (lookahead == 'd') ADVANCE(42);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 3:
      if (lookahead == ',') ADVANCE(54);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == ':') ADVANCE(53);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(57);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(13);
      if (lookahead == 'l') ADVANCE(19);
      if (lookahead == 'n') ADVANCE(55);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 7:
      if (lookahead == 'd') ADVANCE(72);
      END_STATE();
    case 8:
      if (lookahead == 'd') ADVANCE(48);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(69);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(14);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(65);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(49);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(73);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(6);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(52);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 25:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(50);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 29:
      if (lookahead == 'u') ADVANCE(58);
      END_STATE();
    case 30:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 31:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 34:
      if (eof) ADVANCE(35);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '(') ADVANCE(75);
      if (lookahead == ')') ADVANCE(76);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == ':') ADVANCE(53);
      if (lookahead == '=') ADVANCE(60);
      if (lookahead == 'f') ADVANCE(36);
      if (lookahead == 'n') ADVANCE(39);
      if (lookahead == 'p') ADVANCE(45);
      if (lookahead == 't') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(34)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(40);
      if (lookahead == 'n') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_t_void);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_t_bool);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_t_int);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_t_float);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_t_str);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_pu);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_pu);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_int);
      if (lookahead == '.') ADVANCE(62);
      if (lookahead == 'e') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_float_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_float_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_float_token3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_nil);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_nil);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_str);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_do);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_do);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 34},
  [2] = {.lex_state = 34},
  [3] = {.lex_state = 34},
  [4] = {.lex_state = 34},
  [5] = {.lex_state = 34},
  [6] = {.lex_state = 34},
  [7] = {.lex_state = 34},
  [8] = {.lex_state = 34},
  [9] = {.lex_state = 34},
  [10] = {.lex_state = 34},
  [11] = {.lex_state = 34},
  [12] = {.lex_state = 34},
  [13] = {.lex_state = 34},
  [14] = {.lex_state = 34},
  [15] = {.lex_state = 34},
  [16] = {.lex_state = 34},
  [17] = {.lex_state = 34},
  [18] = {.lex_state = 34},
  [19] = {.lex_state = 34},
  [20] = {.lex_state = 34},
  [21] = {.lex_state = 34},
  [22] = {.lex_state = 34},
  [23] = {.lex_state = 34},
  [24] = {.lex_state = 34},
  [25] = {.lex_state = 34},
  [26] = {.lex_state = 34},
  [27] = {.lex_state = 34},
  [28] = {.lex_state = 34},
  [29] = {.lex_state = 34},
  [30] = {.lex_state = 34},
  [31] = {.lex_state = 34},
  [32] = {.lex_state = 34},
  [33] = {.lex_state = 34},
  [34] = {.lex_state = 34},
  [35] = {.lex_state = 34},
  [36] = {.lex_state = 34},
  [37] = {.lex_state = 34},
  [38] = {.lex_state = 34},
  [39] = {.lex_state = 34},
  [40] = {.lex_state = 34},
  [41] = {.lex_state = 34},
  [42] = {.lex_state = 34},
  [43] = {.lex_state = 34},
  [44] = {.lex_state = 34},
  [45] = {.lex_state = 34},
  [46] = {.lex_state = 34},
  [47] = {.lex_state = 34},
  [48] = {.lex_state = 34},
  [49] = {.lex_state = 34},
  [50] = {.lex_state = 34},
  [51] = {.lex_state = 34},
  [52] = {.lex_state = 34},
  [53] = {.lex_state = 34},
  [54] = {.lex_state = 34},
  [55] = {.lex_state = 34},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 2},
  [81] = {.lex_state = 2},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 2},
  [84] = {.lex_state = 3},
  [85] = {.lex_state = 3},
  [86] = {.lex_state = 3},
  [87] = {.lex_state = 3},
  [88] = {.lex_state = 3},
  [89] = {.lex_state = 3},
  [90] = {.lex_state = 2},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 2},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 3},
  [95] = {.lex_state = 2},
  [96] = {.lex_state = 3},
  [97] = {.lex_state = 3},
  [98] = {.lex_state = 2},
  [99] = {.lex_state = 2},
  [100] = {.lex_state = 2},
  [101] = {.lex_state = 3},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 2},
  [104] = {.lex_state = 3},
  [105] = {.lex_state = 3},
  [106] = {.lex_state = 3},
  [107] = {.lex_state = 3},
  [108] = {.lex_state = 3},
  [109] = {.lex_state = 3},
  [110] = {.lex_state = 3},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 3},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 3},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 0},
  [151] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_t_void] = ACTIONS(1),
    [sym_t_bool] = ACTIONS(1),
    [sym_t_int] = ACTIONS(1),
    [sym_t_float] = ACTIONS(1),
    [sym_t_str] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_pu] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [aux_sym_float_token1] = ACTIONS(1),
    [aux_sym_float_token2] = ACTIONS(1),
    [aux_sym_float_token3] = ACTIONS(1),
    [sym_nil] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_str] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(143),
    [sym__inner_statement] = STATE(2),
    [sym__outer_statement] = STATE(2),
    [sym__declaration] = STATE(2),
    [sym_const_declaration] = STATE(2),
    [sym_mut_declaration] = STATE(2),
    [sym_float] = STATE(53),
    [sym_bool] = STATE(53),
    [sym_fn] = STATE(53),
    [sym_pu] = STATE(53),
    [sym__tup_params] = STATE(36),
    [sym_fn_call] = STATE(53),
    [sym_arrow_call] = STATE(53),
    [sym_tup] = STATE(53),
    [sym__expression] = STATE(53),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [anon_sym_pu] = ACTIONS(9),
    [sym_int] = ACTIONS(11),
    [aux_sym_float_token1] = ACTIONS(13),
    [aux_sym_float_token2] = ACTIONS(15),
    [aux_sym_float_token3] = ACTIONS(13),
    [sym_nil] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_str] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
  },
  [2] = {
    [sym__inner_statement] = STATE(3),
    [sym__outer_statement] = STATE(3),
    [sym__declaration] = STATE(3),
    [sym_const_declaration] = STATE(3),
    [sym_mut_declaration] = STATE(3),
    [sym_float] = STATE(53),
    [sym_bool] = STATE(53),
    [sym_fn] = STATE(53),
    [sym_pu] = STATE(53),
    [sym__tup_params] = STATE(36),
    [sym_fn_call] = STATE(53),
    [sym_arrow_call] = STATE(53),
    [sym_tup] = STATE(53),
    [sym__expression] = STATE(53),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [anon_sym_pu] = ACTIONS(9),
    [sym_int] = ACTIONS(11),
    [aux_sym_float_token1] = ACTIONS(13),
    [aux_sym_float_token2] = ACTIONS(15),
    [aux_sym_float_token3] = ACTIONS(13),
    [sym_nil] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_str] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
  },
  [3] = {
    [sym__inner_statement] = STATE(3),
    [sym__outer_statement] = STATE(3),
    [sym__declaration] = STATE(3),
    [sym_const_declaration] = STATE(3),
    [sym_mut_declaration] = STATE(3),
    [sym_float] = STATE(53),
    [sym_bool] = STATE(53),
    [sym_fn] = STATE(53),
    [sym_pu] = STATE(53),
    [sym__tup_params] = STATE(36),
    [sym_fn_call] = STATE(53),
    [sym_arrow_call] = STATE(53),
    [sym_tup] = STATE(53),
    [sym__expression] = STATE(53),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_identifier] = ACTIONS(27),
    [anon_sym_fn] = ACTIONS(30),
    [anon_sym_pu] = ACTIONS(33),
    [sym_int] = ACTIONS(36),
    [aux_sym_float_token1] = ACTIONS(39),
    [aux_sym_float_token2] = ACTIONS(42),
    [aux_sym_float_token3] = ACTIONS(39),
    [sym_nil] = ACTIONS(36),
    [anon_sym_true] = ACTIONS(45),
    [anon_sym_false] = ACTIONS(45),
    [sym_str] = ACTIONS(48),
    [anon_sym_LPAREN] = ACTIONS(51),
  },
  [4] = {
    [sym__inner_statement] = STATE(147),
    [sym__declaration] = STATE(147),
    [sym_const_declaration] = STATE(147),
    [sym_mut_declaration] = STATE(147),
    [sym_float] = STATE(112),
    [sym_bool] = STATE(112),
    [sym__fn_body] = STATE(40),
    [sym_fn] = STATE(112),
    [sym_pu] = STATE(112),
    [sym__tup_params] = STATE(128),
    [sym_fn_call] = STATE(112),
    [sym_arrow_call] = STATE(112),
    [sym_tup] = STATE(112),
    [sym__expression] = STATE(112),
    [sym_identifier] = ACTIONS(54),
    [anon_sym_fn] = ACTIONS(56),
    [anon_sym_pu] = ACTIONS(58),
    [sym_int] = ACTIONS(60),
    [aux_sym_float_token1] = ACTIONS(62),
    [aux_sym_float_token2] = ACTIONS(64),
    [aux_sym_float_token3] = ACTIONS(62),
    [sym_nil] = ACTIONS(60),
    [anon_sym_true] = ACTIONS(66),
    [anon_sym_false] = ACTIONS(66),
    [sym_str] = ACTIONS(68),
    [anon_sym_LPAREN] = ACTIONS(70),
  },
  [5] = {
    [sym__inner_statement] = STATE(146),
    [sym__declaration] = STATE(146),
    [sym_const_declaration] = STATE(146),
    [sym_mut_declaration] = STATE(146),
    [sym_float] = STATE(112),
    [sym_bool] = STATE(112),
    [sym__fn_body] = STATE(117),
    [sym_fn] = STATE(112),
    [sym_pu] = STATE(112),
    [sym__tup_params] = STATE(128),
    [sym_fn_call] = STATE(112),
    [sym_arrow_call] = STATE(112),
    [sym_tup] = STATE(112),
    [sym__expression] = STATE(112),
    [sym_identifier] = ACTIONS(54),
    [anon_sym_fn] = ACTIONS(56),
    [anon_sym_pu] = ACTIONS(58),
    [sym_int] = ACTIONS(60),
    [aux_sym_float_token1] = ACTIONS(62),
    [aux_sym_float_token2] = ACTIONS(64),
    [aux_sym_float_token3] = ACTIONS(62),
    [sym_nil] = ACTIONS(60),
    [anon_sym_true] = ACTIONS(66),
    [anon_sym_false] = ACTIONS(66),
    [sym_str] = ACTIONS(68),
    [anon_sym_LPAREN] = ACTIONS(70),
  },
  [6] = {
    [sym__inner_statement] = STATE(147),
    [sym__declaration] = STATE(147),
    [sym_const_declaration] = STATE(147),
    [sym_mut_declaration] = STATE(147),
    [sym_float] = STATE(112),
    [sym_bool] = STATE(112),
    [sym__fn_body] = STATE(39),
    [sym_fn] = STATE(112),
    [sym_pu] = STATE(112),
    [sym__tup_params] = STATE(128),
    [sym_fn_call] = STATE(112),
    [sym_arrow_call] = STATE(112),
    [sym_tup] = STATE(112),
    [sym__expression] = STATE(112),
    [sym_identifier] = ACTIONS(54),
    [anon_sym_fn] = ACTIONS(56),
    [anon_sym_pu] = ACTIONS(58),
    [sym_int] = ACTIONS(60),
    [aux_sym_float_token1] = ACTIONS(62),
    [aux_sym_float_token2] = ACTIONS(64),
    [aux_sym_float_token3] = ACTIONS(62),
    [sym_nil] = ACTIONS(60),
    [anon_sym_true] = ACTIONS(66),
    [anon_sym_false] = ACTIONS(66),
    [sym_str] = ACTIONS(68),
    [anon_sym_LPAREN] = ACTIONS(70),
  },
  [7] = {
    [sym__inner_statement] = STATE(147),
    [sym__declaration] = STATE(147),
    [sym_const_declaration] = STATE(147),
    [sym_mut_declaration] = STATE(147),
    [sym_float] = STATE(112),
    [sym_bool] = STATE(112),
    [sym__fn_body] = STATE(46),
    [sym_fn] = STATE(112),
    [sym_pu] = STATE(112),
    [sym__tup_params] = STATE(128),
    [sym_fn_call] = STATE(112),
    [sym_arrow_call] = STATE(112),
    [sym_tup] = STATE(112),
    [sym__expression] = STATE(112),
    [sym_identifier] = ACTIONS(54),
    [anon_sym_fn] = ACTIONS(56),
    [anon_sym_pu] = ACTIONS(58),
    [sym_int] = ACTIONS(60),
    [aux_sym_float_token1] = ACTIONS(62),
    [aux_sym_float_token2] = ACTIONS(64),
    [aux_sym_float_token3] = ACTIONS(62),
    [sym_nil] = ACTIONS(60),
    [anon_sym_true] = ACTIONS(66),
    [anon_sym_false] = ACTIONS(66),
    [sym_str] = ACTIONS(68),
    [anon_sym_LPAREN] = ACTIONS(70),
  },
  [8] = {
    [sym__inner_statement] = STATE(147),
    [sym__declaration] = STATE(147),
    [sym_const_declaration] = STATE(147),
    [sym_mut_declaration] = STATE(147),
    [sym_float] = STATE(112),
    [sym_bool] = STATE(112),
    [sym__fn_body] = STATE(45),
    [sym_fn] = STATE(112),
    [sym_pu] = STATE(112),
    [sym__tup_params] = STATE(128),
    [sym_fn_call] = STATE(112),
    [sym_arrow_call] = STATE(112),
    [sym_tup] = STATE(112),
    [sym__expression] = STATE(112),
    [sym_identifier] = ACTIONS(54),
    [anon_sym_fn] = ACTIONS(56),
    [anon_sym_pu] = ACTIONS(58),
    [sym_int] = ACTIONS(60),
    [aux_sym_float_token1] = ACTIONS(62),
    [aux_sym_float_token2] = ACTIONS(64),
    [aux_sym_float_token3] = ACTIONS(62),
    [sym_nil] = ACTIONS(60),
    [anon_sym_true] = ACTIONS(66),
    [anon_sym_false] = ACTIONS(66),
    [sym_str] = ACTIONS(68),
    [anon_sym_LPAREN] = ACTIONS(70),
  },
  [9] = {
    [sym__inner_statement] = STATE(146),
    [sym__declaration] = STATE(146),
    [sym_const_declaration] = STATE(146),
    [sym_mut_declaration] = STATE(146),
    [sym_float] = STATE(112),
    [sym_bool] = STATE(112),
    [sym__fn_body] = STATE(132),
    [sym_fn] = STATE(112),
    [sym_pu] = STATE(112),
    [sym__tup_params] = STATE(128),
    [sym_fn_call] = STATE(112),
    [sym_arrow_call] = STATE(112),
    [sym_tup] = STATE(112),
    [sym__expression] = STATE(112),
    [sym_identifier] = ACTIONS(54),
    [anon_sym_fn] = ACTIONS(56),
    [anon_sym_pu] = ACTIONS(58),
    [sym_int] = ACTIONS(60),
    [aux_sym_float_token1] = ACTIONS(62),
    [aux_sym_float_token2] = ACTIONS(64),
    [aux_sym_float_token3] = ACTIONS(62),
    [sym_nil] = ACTIONS(60),
    [anon_sym_true] = ACTIONS(66),
    [anon_sym_false] = ACTIONS(66),
    [sym_str] = ACTIONS(68),
    [anon_sym_LPAREN] = ACTIONS(70),
  },
  [10] = {
    [sym__inner_statement] = STATE(146),
    [sym__declaration] = STATE(146),
    [sym_const_declaration] = STATE(146),
    [sym_mut_declaration] = STATE(146),
    [sym_float] = STATE(112),
    [sym_bool] = STATE(112),
    [sym__fn_body] = STATE(114),
    [sym_fn] = STATE(112),
    [sym_pu] = STATE(112),
    [sym__tup_params] = STATE(128),
    [sym_fn_call] = STATE(112),
    [sym_arrow_call] = STATE(112),
    [sym_tup] = STATE(112),
    [sym__expression] = STATE(112),
    [sym_identifier] = ACTIONS(54),
    [anon_sym_fn] = ACTIONS(56),
    [anon_sym_pu] = ACTIONS(58),
    [sym_int] = ACTIONS(60),
    [aux_sym_float_token1] = ACTIONS(62),
    [aux_sym_float_token2] = ACTIONS(64),
    [aux_sym_float_token3] = ACTIONS(62),
    [sym_nil] = ACTIONS(60),
    [anon_sym_true] = ACTIONS(66),
    [anon_sym_false] = ACTIONS(66),
    [sym_str] = ACTIONS(68),
    [anon_sym_LPAREN] = ACTIONS(70),
  },
  [11] = {
    [sym__inner_statement] = STATE(146),
    [sym__declaration] = STATE(146),
    [sym_const_declaration] = STATE(146),
    [sym_mut_declaration] = STATE(146),
    [sym_float] = STATE(112),
    [sym_bool] = STATE(112),
    [sym__fn_body] = STATE(130),
    [sym_fn] = STATE(112),
    [sym_pu] = STATE(112),
    [sym__tup_params] = STATE(128),
    [sym_fn_call] = STATE(112),
    [sym_arrow_call] = STATE(112),
    [sym_tup] = STATE(112),
    [sym__expression] = STATE(112),
    [sym_identifier] = ACTIONS(54),
    [anon_sym_fn] = ACTIONS(56),
    [anon_sym_pu] = ACTIONS(58),
    [sym_int] = ACTIONS(60),
    [aux_sym_float_token1] = ACTIONS(62),
    [aux_sym_float_token2] = ACTIONS(64),
    [aux_sym_float_token3] = ACTIONS(62),
    [sym_nil] = ACTIONS(60),
    [anon_sym_true] = ACTIONS(66),
    [anon_sym_false] = ACTIONS(66),
    [sym_str] = ACTIONS(68),
    [anon_sym_LPAREN] = ACTIONS(70),
  },
  [12] = {
    [sym__inner_statement] = STATE(147),
    [sym__declaration] = STATE(147),
    [sym_const_declaration] = STATE(147),
    [sym_mut_declaration] = STATE(147),
    [sym_float] = STATE(112),
    [sym_bool] = STATE(112),
    [sym__fn_body] = STATE(41),
    [sym_fn] = STATE(112),
    [sym_pu] = STATE(112),
    [sym__tup_params] = STATE(128),
    [sym_fn_call] = STATE(112),
    [sym_arrow_call] = STATE(112),
    [sym_tup] = STATE(112),
    [sym__expression] = STATE(112),
    [sym_identifier] = ACTIONS(54),
    [anon_sym_fn] = ACTIONS(56),
    [anon_sym_pu] = ACTIONS(58),
    [sym_int] = ACTIONS(60),
    [aux_sym_float_token1] = ACTIONS(62),
    [aux_sym_float_token2] = ACTIONS(64),
    [aux_sym_float_token3] = ACTIONS(62),
    [sym_nil] = ACTIONS(60),
    [anon_sym_true] = ACTIONS(66),
    [anon_sym_false] = ACTIONS(66),
    [sym_str] = ACTIONS(68),
    [anon_sym_LPAREN] = ACTIONS(70),
  },
  [13] = {
    [sym__inner_statement] = STATE(147),
    [sym__declaration] = STATE(147),
    [sym_const_declaration] = STATE(147),
    [sym_mut_declaration] = STATE(147),
    [sym_float] = STATE(112),
    [sym_bool] = STATE(112),
    [sym__fn_body] = STATE(43),
    [sym_fn] = STATE(112),
    [sym_pu] = STATE(112),
    [sym__tup_params] = STATE(128),
    [sym_fn_call] = STATE(112),
    [sym_arrow_call] = STATE(112),
    [sym_tup] = STATE(112),
    [sym__expression] = STATE(112),
    [sym_identifier] = ACTIONS(54),
    [anon_sym_fn] = ACTIONS(56),
    [anon_sym_pu] = ACTIONS(58),
    [sym_int] = ACTIONS(60),
    [aux_sym_float_token1] = ACTIONS(62),
    [aux_sym_float_token2] = ACTIONS(64),
    [aux_sym_float_token3] = ACTIONS(62),
    [sym_nil] = ACTIONS(60),
    [anon_sym_true] = ACTIONS(66),
    [anon_sym_false] = ACTIONS(66),
    [sym_str] = ACTIONS(68),
    [anon_sym_LPAREN] = ACTIONS(70),
  },
  [14] = {
    [sym__inner_statement] = STATE(146),
    [sym__declaration] = STATE(146),
    [sym_const_declaration] = STATE(146),
    [sym_mut_declaration] = STATE(146),
    [sym_float] = STATE(112),
    [sym_bool] = STATE(112),
    [sym__fn_body] = STATE(139),
    [sym_fn] = STATE(112),
    [sym_pu] = STATE(112),
    [sym__tup_params] = STATE(128),
    [sym_fn_call] = STATE(112),
    [sym_arrow_call] = STATE(112),
    [sym_tup] = STATE(112),
    [sym__expression] = STATE(112),
    [sym_identifier] = ACTIONS(54),
    [anon_sym_fn] = ACTIONS(56),
    [anon_sym_pu] = ACTIONS(58),
    [sym_int] = ACTIONS(60),
    [aux_sym_float_token1] = ACTIONS(62),
    [aux_sym_float_token2] = ACTIONS(64),
    [aux_sym_float_token3] = ACTIONS(62),
    [sym_nil] = ACTIONS(60),
    [anon_sym_true] = ACTIONS(66),
    [anon_sym_false] = ACTIONS(66),
    [sym_str] = ACTIONS(68),
    [anon_sym_LPAREN] = ACTIONS(70),
  },
  [15] = {
    [sym__inner_statement] = STATE(146),
    [sym__declaration] = STATE(146),
    [sym_const_declaration] = STATE(146),
    [sym_mut_declaration] = STATE(146),
    [sym_float] = STATE(112),
    [sym_bool] = STATE(112),
    [sym__fn_body] = STATE(118),
    [sym_fn] = STATE(112),
    [sym_pu] = STATE(112),
    [sym__tup_params] = STATE(128),
    [sym_fn_call] = STATE(112),
    [sym_arrow_call] = STATE(112),
    [sym_tup] = STATE(112),
    [sym__expression] = STATE(112),
    [sym_identifier] = ACTIONS(54),
    [anon_sym_fn] = ACTIONS(56),
    [anon_sym_pu] = ACTIONS(58),
    [sym_int] = ACTIONS(60),
    [aux_sym_float_token1] = ACTIONS(62),
    [aux_sym_float_token2] = ACTIONS(64),
    [aux_sym_float_token3] = ACTIONS(62),
    [sym_nil] = ACTIONS(60),
    [anon_sym_true] = ACTIONS(66),
    [anon_sym_false] = ACTIONS(66),
    [sym_str] = ACTIONS(68),
    [anon_sym_LPAREN] = ACTIONS(70),
  },
  [16] = {
    [sym__inner_statement] = STATE(147),
    [sym__declaration] = STATE(147),
    [sym_const_declaration] = STATE(147),
    [sym_mut_declaration] = STATE(147),
    [sym_float] = STATE(112),
    [sym_bool] = STATE(112),
    [sym__fn_body] = STATE(38),
    [sym_fn] = STATE(112),
    [sym_pu] = STATE(112),
    [sym__tup_params] = STATE(128),
    [sym_fn_call] = STATE(112),
    [sym_arrow_call] = STATE(112),
    [sym_tup] = STATE(112),
    [sym__expression] = STATE(112),
    [sym_identifier] = ACTIONS(54),
    [anon_sym_fn] = ACTIONS(56),
    [anon_sym_pu] = ACTIONS(58),
    [sym_int] = ACTIONS(60),
    [aux_sym_float_token1] = ACTIONS(62),
    [aux_sym_float_token2] = ACTIONS(64),
    [aux_sym_float_token3] = ACTIONS(62),
    [sym_nil] = ACTIONS(60),
    [anon_sym_true] = ACTIONS(66),
    [anon_sym_false] = ACTIONS(66),
    [sym_str] = ACTIONS(68),
    [anon_sym_LPAREN] = ACTIONS(70),
  },
  [17] = {
    [sym__inner_statement] = STATE(147),
    [sym__declaration] = STATE(147),
    [sym_const_declaration] = STATE(147),
    [sym_mut_declaration] = STATE(147),
    [sym_float] = STATE(112),
    [sym_bool] = STATE(112),
    [sym__fn_body] = STATE(42),
    [sym_fn] = STATE(112),
    [sym_pu] = STATE(112),
    [sym__tup_params] = STATE(128),
    [sym_fn_call] = STATE(112),
    [sym_arrow_call] = STATE(112),
    [sym_tup] = STATE(112),
    [sym__expression] = STATE(112),
    [sym_identifier] = ACTIONS(54),
    [anon_sym_fn] = ACTIONS(56),
    [anon_sym_pu] = ACTIONS(58),
    [sym_int] = ACTIONS(60),
    [aux_sym_float_token1] = ACTIONS(62),
    [aux_sym_float_token2] = ACTIONS(64),
    [aux_sym_float_token3] = ACTIONS(62),
    [sym_nil] = ACTIONS(60),
    [anon_sym_true] = ACTIONS(66),
    [anon_sym_false] = ACTIONS(66),
    [sym_str] = ACTIONS(68),
    [anon_sym_LPAREN] = ACTIONS(70),
  },
  [18] = {
    [sym__inner_statement] = STATE(146),
    [sym__declaration] = STATE(146),
    [sym_const_declaration] = STATE(146),
    [sym_mut_declaration] = STATE(146),
    [sym_float] = STATE(112),
    [sym_bool] = STATE(112),
    [sym__fn_body] = STATE(122),
    [sym_fn] = STATE(112),
    [sym_pu] = STATE(112),
    [sym__tup_params] = STATE(128),
    [sym_fn_call] = STATE(112),
    [sym_arrow_call] = STATE(112),
    [sym_tup] = STATE(112),
    [sym__expression] = STATE(112),
    [sym_identifier] = ACTIONS(54),
    [anon_sym_fn] = ACTIONS(56),
    [anon_sym_pu] = ACTIONS(58),
    [sym_int] = ACTIONS(60),
    [aux_sym_float_token1] = ACTIONS(62),
    [aux_sym_float_token2] = ACTIONS(64),
    [aux_sym_float_token3] = ACTIONS(62),
    [sym_nil] = ACTIONS(60),
    [anon_sym_true] = ACTIONS(66),
    [anon_sym_false] = ACTIONS(66),
    [sym_str] = ACTIONS(68),
    [anon_sym_LPAREN] = ACTIONS(70),
  },
  [19] = {
    [sym__inner_statement] = STATE(146),
    [sym__declaration] = STATE(146),
    [sym_const_declaration] = STATE(146),
    [sym_mut_declaration] = STATE(146),
    [sym_float] = STATE(112),
    [sym_bool] = STATE(112),
    [sym__fn_body] = STATE(113),
    [sym_fn] = STATE(112),
    [sym_pu] = STATE(112),
    [sym__tup_params] = STATE(128),
    [sym_fn_call] = STATE(112),
    [sym_arrow_call] = STATE(112),
    [sym_tup] = STATE(112),
    [sym__expression] = STATE(112),
    [sym_identifier] = ACTIONS(54),
    [anon_sym_fn] = ACTIONS(56),
    [anon_sym_pu] = ACTIONS(58),
    [sym_int] = ACTIONS(60),
    [aux_sym_float_token1] = ACTIONS(62),
    [aux_sym_float_token2] = ACTIONS(64),
    [aux_sym_float_token3] = ACTIONS(62),
    [sym_nil] = ACTIONS(60),
    [anon_sym_true] = ACTIONS(66),
    [anon_sym_false] = ACTIONS(66),
    [sym_str] = ACTIONS(68),
    [anon_sym_LPAREN] = ACTIONS(70),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_pu,
    ACTIONS(15), 1,
      aux_sym_float_token2,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      sym_identifier,
    ACTIONS(76), 1,
      sym_str,
    STATE(36), 1,
      sym__tup_params,
    ACTIONS(13), 2,
      aux_sym_float_token1,
      aux_sym_float_token3,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(74), 2,
      sym_int,
      sym_nil,
    STATE(50), 8,
      sym_float,
      sym_bool,
      sym_fn,
      sym_pu,
      sym_fn_call,
      sym_arrow_call,
      sym_tup,
      sym__expression,
  [44] = 11,
    ACTIONS(56), 1,
      anon_sym_fn,
    ACTIONS(58), 1,
      anon_sym_pu,
    ACTIONS(64), 1,
      aux_sym_float_token2,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(82), 1,
      sym_str,
    STATE(128), 1,
      sym__tup_params,
    ACTIONS(62), 2,
      aux_sym_float_token1,
      aux_sym_float_token3,
    ACTIONS(66), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(80), 2,
      sym_int,
      sym_nil,
    STATE(116), 8,
      sym_float,
      sym_bool,
      sym_fn,
      sym_pu,
      sym_fn_call,
      sym_arrow_call,
      sym_tup,
      sym__expression,
  [88] = 11,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_pu,
    ACTIONS(15), 1,
      aux_sym_float_token2,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      sym_identifier,
    ACTIONS(86), 1,
      sym_str,
    STATE(36), 1,
      sym__tup_params,
    ACTIONS(13), 2,
      aux_sym_float_token1,
      aux_sym_float_token3,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(84), 2,
      sym_int,
      sym_nil,
    STATE(123), 8,
      sym_float,
      sym_bool,
      sym_fn,
      sym_pu,
      sym_fn_call,
      sym_arrow_call,
      sym_tup,
      sym__expression,
  [132] = 11,
    ACTIONS(56), 1,
      anon_sym_fn,
    ACTIONS(58), 1,
      anon_sym_pu,
    ACTIONS(64), 1,
      aux_sym_float_token2,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(90), 1,
      sym_str,
    STATE(128), 1,
      sym__tup_params,
    ACTIONS(62), 2,
      aux_sym_float_token1,
      aux_sym_float_token3,
    ACTIONS(66), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(88), 2,
      sym_int,
      sym_nil,
    STATE(115), 8,
      sym_float,
      sym_bool,
      sym_fn,
      sym_pu,
      sym_fn_call,
      sym_arrow_call,
      sym_tup,
      sym__expression,
  [176] = 11,
    ACTIONS(56), 1,
      anon_sym_fn,
    ACTIONS(58), 1,
      anon_sym_pu,
    ACTIONS(64), 1,
      aux_sym_float_token2,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(94), 1,
      sym_str,
    STATE(128), 1,
      sym__tup_params,
    ACTIONS(62), 2,
      aux_sym_float_token1,
      aux_sym_float_token3,
    ACTIONS(66), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(92), 2,
      sym_int,
      sym_nil,
    STATE(111), 8,
      sym_float,
      sym_bool,
      sym_fn,
      sym_pu,
      sym_fn_call,
      sym_arrow_call,
      sym_tup,
      sym__expression,
  [220] = 11,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_pu,
    ACTIONS(15), 1,
      aux_sym_float_token2,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      sym_identifier,
    ACTIONS(98), 1,
      sym_str,
    STATE(36), 1,
      sym__tup_params,
    ACTIONS(13), 2,
      aux_sym_float_token1,
      aux_sym_float_token3,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(96), 2,
      sym_int,
      sym_nil,
    STATE(51), 8,
      sym_float,
      sym_bool,
      sym_fn,
      sym_pu,
      sym_fn_call,
      sym_arrow_call,
      sym_tup,
      sym__expression,
  [264] = 11,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_pu,
    ACTIONS(15), 1,
      aux_sym_float_token2,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      sym_identifier,
    ACTIONS(102), 1,
      sym_str,
    STATE(36), 1,
      sym__tup_params,
    ACTIONS(13), 2,
      aux_sym_float_token1,
      aux_sym_float_token3,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(100), 2,
      sym_int,
      sym_nil,
    STATE(54), 8,
      sym_float,
      sym_bool,
      sym_fn,
      sym_pu,
      sym_fn_call,
      sym_arrow_call,
      sym_tup,
      sym__expression,
  [308] = 11,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_pu,
    ACTIONS(15), 1,
      aux_sym_float_token2,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      sym_identifier,
    ACTIONS(106), 1,
      sym_str,
    STATE(36), 1,
      sym__tup_params,
    ACTIONS(13), 2,
      aux_sym_float_token1,
      aux_sym_float_token3,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(104), 2,
      sym_int,
      sym_nil,
    STATE(126), 8,
      sym_float,
      sym_bool,
      sym_fn,
      sym_pu,
      sym_fn_call,
      sym_arrow_call,
      sym_tup,
      sym__expression,
  [352] = 11,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_pu,
    ACTIONS(15), 1,
      aux_sym_float_token2,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      sym_identifier,
    ACTIONS(110), 1,
      sym_str,
    STATE(36), 1,
      sym__tup_params,
    ACTIONS(13), 2,
      aux_sym_float_token1,
      aux_sym_float_token3,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(108), 2,
      sym_int,
      sym_nil,
    STATE(52), 8,
      sym_float,
      sym_bool,
      sym_fn,
      sym_pu,
      sym_fn_call,
      sym_arrow_call,
      sym_tup,
      sym__expression,
  [396] = 11,
    ACTIONS(56), 1,
      anon_sym_fn,
    ACTIONS(58), 1,
      anon_sym_pu,
    ACTIONS(64), 1,
      aux_sym_float_token2,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(114), 1,
      sym_str,
    STATE(128), 1,
      sym__tup_params,
    ACTIONS(62), 2,
      aux_sym_float_token1,
      aux_sym_float_token3,
    ACTIONS(66), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(112), 2,
      sym_int,
      sym_nil,
    STATE(121), 8,
      sym_float,
      sym_bool,
      sym_fn,
      sym_pu,
      sym_fn_call,
      sym_arrow_call,
      sym_tup,
      sym__expression,
  [440] = 4,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    STATE(33), 1,
      sym__tup_params,
    ACTIONS(116), 6,
      ts_builtin_sym_end,
      anon_sym_DASH_GT,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
      anon_sym_RPAREN,
    ACTIONS(118), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [465] = 5,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(120), 1,
      anon_sym_COLON,
    STATE(33), 1,
      sym__tup_params,
    ACTIONS(116), 5,
      ts_builtin_sym_end,
      anon_sym_DASH_GT,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
    ACTIONS(118), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [492] = 2,
    ACTIONS(122), 7,
      ts_builtin_sym_end,
      anon_sym_DASH_GT,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(124), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [512] = 2,
    ACTIONS(126), 7,
      ts_builtin_sym_end,
      anon_sym_DASH_GT,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(128), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [532] = 2,
    ACTIONS(130), 7,
      ts_builtin_sym_end,
      anon_sym_DASH_GT,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(132), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [552] = 2,
    ACTIONS(134), 7,
      ts_builtin_sym_end,
      anon_sym_DASH_GT,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(136), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [572] = 2,
    ACTIONS(138), 7,
      ts_builtin_sym_end,
      anon_sym_DASH_GT,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(140), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [592] = 2,
    ACTIONS(142), 7,
      ts_builtin_sym_end,
      anon_sym_DASH_GT,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(144), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [612] = 2,
    ACTIONS(146), 7,
      ts_builtin_sym_end,
      anon_sym_DASH_GT,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(148), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [632] = 2,
    ACTIONS(150), 7,
      ts_builtin_sym_end,
      anon_sym_DASH_GT,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(152), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [652] = 2,
    ACTIONS(154), 7,
      ts_builtin_sym_end,
      anon_sym_DASH_GT,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(156), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [672] = 2,
    ACTIONS(158), 7,
      ts_builtin_sym_end,
      anon_sym_DASH_GT,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(160), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [692] = 2,
    ACTIONS(162), 7,
      ts_builtin_sym_end,
      anon_sym_DASH_GT,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(164), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [712] = 2,
    ACTIONS(166), 7,
      ts_builtin_sym_end,
      anon_sym_DASH_GT,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(168), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [732] = 2,
    ACTIONS(170), 7,
      ts_builtin_sym_end,
      anon_sym_DASH_GT,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(172), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [752] = 2,
    ACTIONS(174), 7,
      ts_builtin_sym_end,
      anon_sym_DASH_GT,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(176), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [772] = 2,
    ACTIONS(178), 7,
      ts_builtin_sym_end,
      anon_sym_DASH_GT,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(180), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [792] = 2,
    ACTIONS(184), 6,
      anon_sym_COLON,
      anon_sym_EQ,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
      anon_sym_LPAREN,
    ACTIONS(182), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [811] = 2,
    ACTIONS(188), 6,
      anon_sym_COLON,
      anon_sym_EQ,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
      anon_sym_LPAREN,
    ACTIONS(186), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [830] = 2,
    ACTIONS(192), 6,
      anon_sym_COLON,
      anon_sym_EQ,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
      anon_sym_LPAREN,
    ACTIONS(190), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [849] = 3,
    ACTIONS(198), 1,
      anon_sym_DASH_GT,
    ACTIONS(194), 5,
      ts_builtin_sym_end,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
      anon_sym_LPAREN,
    ACTIONS(196), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [870] = 3,
    ACTIONS(198), 1,
      anon_sym_DASH_GT,
    ACTIONS(200), 5,
      ts_builtin_sym_end,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
      anon_sym_LPAREN,
    ACTIONS(202), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [891] = 3,
    ACTIONS(198), 1,
      anon_sym_DASH_GT,
    ACTIONS(204), 5,
      ts_builtin_sym_end,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
      anon_sym_LPAREN,
    ACTIONS(206), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [912] = 3,
    ACTIONS(198), 1,
      anon_sym_DASH_GT,
    ACTIONS(208), 5,
      ts_builtin_sym_end,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
      anon_sym_LPAREN,
    ACTIONS(210), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [933] = 3,
    ACTIONS(198), 1,
      anon_sym_DASH_GT,
    ACTIONS(212), 5,
      ts_builtin_sym_end,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
      anon_sym_LPAREN,
    ACTIONS(214), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [954] = 2,
    ACTIONS(218), 6,
      anon_sym_COLON,
      anon_sym_EQ,
      aux_sym_float_token1,
      aux_sym_float_token3,
      sym_str,
      anon_sym_LPAREN,
    ACTIONS(216), 8,
      sym_identifier,
      anon_sym_fn,
      anon_sym_pu,
      sym_int,
      aux_sym_float_token2,
      sym_nil,
      anon_sym_true,
      anon_sym_false,
  [973] = 6,
    ACTIONS(222), 1,
      anon_sym_COLON,
    ACTIONS(224), 1,
      anon_sym_fn,
    ACTIONS(226), 1,
      anon_sym_pu,
    ACTIONS(228), 1,
      anon_sym_EQ,
    STATE(127), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(220), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [999] = 6,
    ACTIONS(224), 1,
      anon_sym_fn,
    ACTIONS(226), 1,
      anon_sym_pu,
    ACTIONS(232), 1,
      anon_sym_COLON,
    ACTIONS(234), 1,
      anon_sym_EQ,
    STATE(141), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(230), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [1025] = 4,
    ACTIONS(238), 1,
      anon_sym_fn,
    ACTIONS(240), 1,
      anon_sym_pu,
    STATE(104), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(236), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [1045] = 4,
    ACTIONS(238), 1,
      anon_sym_fn,
    ACTIONS(240), 1,
      anon_sym_pu,
    STATE(105), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(242), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [1065] = 4,
    ACTIONS(224), 1,
      anon_sym_fn,
    ACTIONS(226), 1,
      anon_sym_pu,
    STATE(12), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(244), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [1085] = 4,
    ACTIONS(224), 1,
      anon_sym_fn,
    ACTIONS(226), 1,
      anon_sym_pu,
    STATE(18), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(246), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [1105] = 4,
    ACTIONS(224), 1,
      anon_sym_fn,
    ACTIONS(226), 1,
      anon_sym_pu,
    STATE(11), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(248), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [1125] = 4,
    ACTIONS(224), 1,
      anon_sym_fn,
    ACTIONS(226), 1,
      anon_sym_pu,
    STATE(48), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(250), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [1145] = 4,
    ACTIONS(224), 1,
      anon_sym_fn,
    ACTIONS(226), 1,
      anon_sym_pu,
    STATE(55), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(252), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [1165] = 4,
    ACTIONS(224), 1,
      anon_sym_fn,
    ACTIONS(226), 1,
      anon_sym_pu,
    STATE(8), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(254), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [1185] = 4,
    ACTIONS(224), 1,
      anon_sym_fn,
    ACTIONS(226), 1,
      anon_sym_pu,
    STATE(47), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(256), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [1205] = 4,
    ACTIONS(224), 1,
      anon_sym_fn,
    ACTIONS(226), 1,
      anon_sym_pu,
    STATE(49), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(258), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [1225] = 4,
    ACTIONS(238), 1,
      anon_sym_fn,
    ACTIONS(240), 1,
      anon_sym_pu,
    STATE(110), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(260), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [1245] = 4,
    ACTIONS(264), 1,
      anon_sym_fn,
    ACTIONS(266), 1,
      anon_sym_pu,
    STATE(103), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(262), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [1265] = 4,
    ACTIONS(224), 1,
      anon_sym_fn,
    ACTIONS(226), 1,
      anon_sym_pu,
    STATE(5), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(268), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [1285] = 4,
    ACTIONS(264), 1,
      anon_sym_fn,
    ACTIONS(266), 1,
      anon_sym_pu,
    STATE(100), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(270), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [1305] = 4,
    ACTIONS(264), 1,
      anon_sym_fn,
    ACTIONS(266), 1,
      anon_sym_pu,
    STATE(93), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(272), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [1325] = 4,
    ACTIONS(238), 1,
      anon_sym_fn,
    ACTIONS(240), 1,
      anon_sym_pu,
    STATE(109), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(274), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [1345] = 4,
    ACTIONS(224), 1,
      anon_sym_fn,
    ACTIONS(226), 1,
      anon_sym_pu,
    STATE(13), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(276), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [1365] = 4,
    ACTIONS(238), 1,
      anon_sym_fn,
    ACTIONS(240), 1,
      anon_sym_pu,
    STATE(108), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(278), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [1385] = 4,
    ACTIONS(264), 1,
      anon_sym_fn,
    ACTIONS(266), 1,
      anon_sym_pu,
    STATE(98), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(280), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [1405] = 4,
    ACTIONS(224), 1,
      anon_sym_fn,
    ACTIONS(226), 1,
      anon_sym_pu,
    STATE(15), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(282), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [1425] = 4,
    ACTIONS(224), 1,
      anon_sym_fn,
    ACTIONS(226), 1,
      anon_sym_pu,
    STATE(16), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(284), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [1445] = 4,
    ACTIONS(264), 1,
      anon_sym_fn,
    ACTIONS(266), 1,
      anon_sym_pu,
    STATE(99), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(286), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [1465] = 7,
    ACTIONS(288), 1,
      sym_identifier,
    ACTIONS(290), 1,
      anon_sym_COMMA,
    ACTIONS(292), 1,
      anon_sym_DASH_GT,
    ACTIONS(294), 1,
      anon_sym_do,
    STATE(95), 1,
      sym_parameter,
    STATE(96), 1,
      aux_sym_parameters_repeat1,
    STATE(137), 1,
      sym_parameters,
  [1487] = 7,
    ACTIONS(288), 1,
      sym_identifier,
    ACTIONS(290), 1,
      anon_sym_COMMA,
    ACTIONS(296), 1,
      anon_sym_DASH_GT,
    ACTIONS(298), 1,
      anon_sym_do,
    STATE(95), 1,
      sym_parameter,
    STATE(96), 1,
      aux_sym_parameters_repeat1,
    STATE(140), 1,
      sym_parameters,
  [1509] = 7,
    ACTIONS(288), 1,
      sym_identifier,
    ACTIONS(290), 1,
      anon_sym_COMMA,
    ACTIONS(300), 1,
      anon_sym_DASH_GT,
    ACTIONS(302), 1,
      anon_sym_do,
    STATE(95), 1,
      sym_parameter,
    STATE(96), 1,
      aux_sym_parameters_repeat1,
    STATE(133), 1,
      sym_parameters,
  [1531] = 7,
    ACTIONS(288), 1,
      sym_identifier,
    ACTIONS(290), 1,
      anon_sym_COMMA,
    ACTIONS(304), 1,
      anon_sym_DASH_GT,
    ACTIONS(306), 1,
      anon_sym_do,
    STATE(95), 1,
      sym_parameter,
    STATE(96), 1,
      aux_sym_parameters_repeat1,
    STATE(135), 1,
      sym_parameters,
  [1553] = 6,
    ACTIONS(308), 1,
      sym_identifier,
    ACTIONS(310), 1,
      anon_sym_COMMA,
    ACTIONS(312), 1,
      anon_sym_DASH_GT,
    STATE(94), 1,
      aux_sym_parameters_repeat1,
    STATE(106), 1,
      sym_parameter,
    STATE(151), 1,
      sym_parameters,
  [1572] = 6,
    ACTIONS(308), 1,
      sym_identifier,
    ACTIONS(310), 1,
      anon_sym_COMMA,
    ACTIONS(314), 1,
      anon_sym_DASH_GT,
    STATE(94), 1,
      aux_sym_parameters_repeat1,
    STATE(106), 1,
      sym_parameter,
    STATE(149), 1,
      sym_parameters,
  [1591] = 6,
    ACTIONS(308), 1,
      sym_identifier,
    ACTIONS(310), 1,
      anon_sym_COMMA,
    ACTIONS(316), 1,
      anon_sym_DASH_GT,
    STATE(94), 1,
      aux_sym_parameters_repeat1,
    STATE(106), 1,
      sym_parameter,
    STATE(144), 1,
      sym_parameters,
  [1610] = 6,
    ACTIONS(308), 1,
      sym_identifier,
    ACTIONS(310), 1,
      anon_sym_COMMA,
    ACTIONS(318), 1,
      anon_sym_DASH_GT,
    STATE(94), 1,
      aux_sym_parameters_repeat1,
    STATE(106), 1,
      sym_parameter,
    STATE(150), 1,
      sym_parameters,
  [1629] = 6,
    ACTIONS(308), 1,
      sym_identifier,
    ACTIONS(310), 1,
      anon_sym_COMMA,
    ACTIONS(320), 1,
      anon_sym_DASH_GT,
    STATE(94), 1,
      aux_sym_parameters_repeat1,
    STATE(106), 1,
      sym_parameter,
    STATE(148), 1,
      sym_parameters,
  [1648] = 6,
    ACTIONS(308), 1,
      sym_identifier,
    ACTIONS(310), 1,
      anon_sym_COMMA,
    ACTIONS(322), 1,
      anon_sym_DASH_GT,
    STATE(94), 1,
      aux_sym_parameters_repeat1,
    STATE(106), 1,
      sym_parameter,
    STATE(145), 1,
      sym_parameters,
  [1667] = 3,
    ACTIONS(326), 1,
      anon_sym_COLON,
    ACTIONS(324), 2,
      sym_identifier,
      anon_sym_do,
    ACTIONS(328), 2,
      anon_sym_COMMA,
      anon_sym_DASH_GT,
  [1679] = 4,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(330), 1,
      anon_sym_COLON,
    STATE(125), 1,
      sym__tup_params,
    ACTIONS(116), 2,
      anon_sym_DASH_GT,
      anon_sym_end,
  [1693] = 4,
    ACTIONS(332), 1,
      sym_identifier,
    ACTIONS(334), 1,
      anon_sym_COMMA,
    ACTIONS(336), 1,
      anon_sym_DASH_GT,
    ACTIONS(338), 1,
      anon_sym_do,
  [1706] = 2,
    ACTIONS(182), 2,
      sym_identifier,
      anon_sym_do,
    ACTIONS(184), 2,
      anon_sym_COMMA,
      anon_sym_DASH_GT,
  [1715] = 4,
    ACTIONS(308), 1,
      sym_identifier,
    ACTIONS(340), 1,
      anon_sym_COMMA,
    STATE(97), 1,
      aux_sym_parameters_repeat1,
    STATE(107), 1,
      sym_parameter,
  [1728] = 4,
    ACTIONS(332), 1,
      sym_identifier,
    ACTIONS(334), 1,
      anon_sym_COMMA,
    ACTIONS(342), 1,
      anon_sym_DASH_GT,
    ACTIONS(344), 1,
      anon_sym_do,
  [1741] = 4,
    ACTIONS(340), 1,
      anon_sym_COMMA,
    ACTIONS(346), 1,
      sym_identifier,
    STATE(92), 1,
      sym_parameter,
    STATE(97), 1,
      aux_sym_parameters_repeat1,
  [1754] = 3,
    ACTIONS(348), 1,
      sym_identifier,
    ACTIONS(351), 1,
      anon_sym_COMMA,
    STATE(97), 2,
      sym_parameter,
      aux_sym_parameters_repeat1,
  [1765] = 2,
    ACTIONS(354), 2,
      sym_identifier,
      anon_sym_do,
    ACTIONS(356), 2,
      anon_sym_COMMA,
      anon_sym_DASH_GT,
  [1774] = 2,
    ACTIONS(190), 2,
      sym_identifier,
      anon_sym_do,
    ACTIONS(192), 2,
      anon_sym_COMMA,
      anon_sym_DASH_GT,
  [1783] = 2,
    ACTIONS(186), 2,
      sym_identifier,
      anon_sym_do,
    ACTIONS(188), 2,
      anon_sym_COMMA,
      anon_sym_DASH_GT,
  [1792] = 2,
    ACTIONS(358), 1,
      anon_sym_COLON,
    ACTIONS(328), 3,
      sym_identifier,
      anon_sym_COMMA,
      anon_sym_DASH_GT,
  [1801] = 3,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    STATE(125), 1,
      sym__tup_params,
    ACTIONS(116), 2,
      anon_sym_DASH_GT,
      anon_sym_end,
  [1812] = 2,
    ACTIONS(216), 2,
      sym_identifier,
      anon_sym_do,
    ACTIONS(218), 2,
      anon_sym_COMMA,
      anon_sym_DASH_GT,
  [1821] = 1,
    ACTIONS(356), 3,
      sym_identifier,
      anon_sym_COMMA,
      anon_sym_DASH_GT,
  [1827] = 1,
    ACTIONS(184), 3,
      sym_identifier,
      anon_sym_COMMA,
      anon_sym_DASH_GT,
  [1833] = 2,
    ACTIONS(342), 1,
      anon_sym_DASH_GT,
    ACTIONS(334), 2,
      sym_identifier,
      anon_sym_COMMA,
  [1841] = 2,
    ACTIONS(336), 1,
      anon_sym_DASH_GT,
    ACTIONS(334), 2,
      sym_identifier,
      anon_sym_COMMA,
  [1849] = 1,
    ACTIONS(192), 3,
      sym_identifier,
      anon_sym_COMMA,
      anon_sym_DASH_GT,
  [1855] = 1,
    ACTIONS(188), 3,
      sym_identifier,
      anon_sym_COMMA,
      anon_sym_DASH_GT,
  [1861] = 1,
    ACTIONS(218), 3,
      sym_identifier,
      anon_sym_COMMA,
      anon_sym_DASH_GT,
  [1867] = 2,
    ACTIONS(212), 1,
      anon_sym_end,
    ACTIONS(360), 1,
      anon_sym_DASH_GT,
  [1874] = 2,
    ACTIONS(208), 1,
      anon_sym_end,
    ACTIONS(360), 1,
      anon_sym_DASH_GT,
  [1881] = 1,
    ACTIONS(178), 2,
      anon_sym_DASH_GT,
      anon_sym_end,
  [1886] = 1,
    ACTIONS(162), 2,
      anon_sym_DASH_GT,
      anon_sym_end,
  [1891] = 2,
    ACTIONS(194), 1,
      anon_sym_end,
    ACTIONS(360), 1,
      anon_sym_DASH_GT,
  [1898] = 2,
    ACTIONS(204), 1,
      anon_sym_end,
    ACTIONS(360), 1,
      anon_sym_DASH_GT,
  [1905] = 1,
    ACTIONS(166), 2,
      anon_sym_DASH_GT,
      anon_sym_end,
  [1910] = 1,
    ACTIONS(158), 2,
      anon_sym_DASH_GT,
      anon_sym_end,
  [1915] = 1,
    ACTIONS(170), 2,
      anon_sym_DASH_GT,
      anon_sym_end,
  [1920] = 1,
    ACTIONS(122), 2,
      anon_sym_DASH_GT,
      anon_sym_end,
  [1925] = 2,
    ACTIONS(200), 1,
      anon_sym_end,
    ACTIONS(360), 1,
      anon_sym_DASH_GT,
  [1932] = 1,
    ACTIONS(174), 2,
      anon_sym_DASH_GT,
      anon_sym_end,
  [1937] = 2,
    ACTIONS(198), 1,
      anon_sym_DASH_GT,
    ACTIONS(362), 1,
      anon_sym_RPAREN,
  [1944] = 2,
    ACTIONS(364), 1,
      sym_identifier,
    STATE(120), 1,
      sym_fn_call,
  [1951] = 1,
    ACTIONS(126), 2,
      anon_sym_DASH_GT,
      anon_sym_end,
  [1956] = 2,
    ACTIONS(198), 1,
      anon_sym_DASH_GT,
    ACTIONS(366), 1,
      anon_sym_RPAREN,
  [1963] = 2,
    ACTIONS(368), 1,
      anon_sym_COLON,
    ACTIONS(370), 1,
      anon_sym_EQ,
  [1970] = 1,
    ACTIONS(138), 2,
      anon_sym_DASH_GT,
      anon_sym_end,
  [1975] = 1,
    ACTIONS(134), 2,
      anon_sym_DASH_GT,
      anon_sym_end,
  [1980] = 1,
    ACTIONS(146), 2,
      anon_sym_DASH_GT,
      anon_sym_end,
  [1985] = 1,
    ACTIONS(130), 2,
      anon_sym_DASH_GT,
      anon_sym_end,
  [1990] = 1,
    ACTIONS(154), 2,
      anon_sym_DASH_GT,
      anon_sym_end,
  [1995] = 2,
    ACTIONS(372), 1,
      anon_sym_DASH_GT,
    ACTIONS(374), 1,
      anon_sym_do,
  [2002] = 2,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    STATE(125), 1,
      sym__tup_params,
  [2009] = 2,
    ACTIONS(376), 1,
      anon_sym_DASH_GT,
    ACTIONS(378), 1,
      anon_sym_do,
  [2016] = 1,
    ACTIONS(142), 2,
      anon_sym_DASH_GT,
      anon_sym_end,
  [2021] = 2,
    ACTIONS(380), 1,
      anon_sym_DASH_GT,
    ACTIONS(382), 1,
      anon_sym_do,
  [2028] = 2,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    STATE(33), 1,
      sym__tup_params,
  [2035] = 1,
    ACTIONS(150), 2,
      anon_sym_DASH_GT,
      anon_sym_end,
  [2040] = 2,
    ACTIONS(384), 1,
      anon_sym_DASH_GT,
    ACTIONS(386), 1,
      anon_sym_do,
  [2047] = 2,
    ACTIONS(388), 1,
      anon_sym_COLON,
    ACTIONS(390), 1,
      anon_sym_EQ,
  [2054] = 2,
    ACTIONS(392), 1,
      sym_identifier,
    STATE(32), 1,
      sym_fn_call,
  [2061] = 1,
    ACTIONS(394), 1,
      ts_builtin_sym_end,
  [2065] = 1,
    ACTIONS(396), 1,
      anon_sym_DASH_GT,
  [2069] = 1,
    ACTIONS(398), 1,
      anon_sym_DASH_GT,
  [2073] = 1,
    ACTIONS(400), 1,
      anon_sym_end,
  [2077] = 1,
    ACTIONS(402), 1,
      anon_sym_end,
  [2081] = 1,
    ACTIONS(404), 1,
      anon_sym_DASH_GT,
  [2085] = 1,
    ACTIONS(406), 1,
      anon_sym_DASH_GT,
  [2089] = 1,
    ACTIONS(408), 1,
      anon_sym_DASH_GT,
  [2093] = 1,
    ACTIONS(410), 1,
      anon_sym_DASH_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(20)] = 0,
  [SMALL_STATE(21)] = 44,
  [SMALL_STATE(22)] = 88,
  [SMALL_STATE(23)] = 132,
  [SMALL_STATE(24)] = 176,
  [SMALL_STATE(25)] = 220,
  [SMALL_STATE(26)] = 264,
  [SMALL_STATE(27)] = 308,
  [SMALL_STATE(28)] = 352,
  [SMALL_STATE(29)] = 396,
  [SMALL_STATE(30)] = 440,
  [SMALL_STATE(31)] = 465,
  [SMALL_STATE(32)] = 492,
  [SMALL_STATE(33)] = 512,
  [SMALL_STATE(34)] = 532,
  [SMALL_STATE(35)] = 552,
  [SMALL_STATE(36)] = 572,
  [SMALL_STATE(37)] = 592,
  [SMALL_STATE(38)] = 612,
  [SMALL_STATE(39)] = 632,
  [SMALL_STATE(40)] = 652,
  [SMALL_STATE(41)] = 672,
  [SMALL_STATE(42)] = 692,
  [SMALL_STATE(43)] = 712,
  [SMALL_STATE(44)] = 732,
  [SMALL_STATE(45)] = 752,
  [SMALL_STATE(46)] = 772,
  [SMALL_STATE(47)] = 792,
  [SMALL_STATE(48)] = 811,
  [SMALL_STATE(49)] = 830,
  [SMALL_STATE(50)] = 849,
  [SMALL_STATE(51)] = 870,
  [SMALL_STATE(52)] = 891,
  [SMALL_STATE(53)] = 912,
  [SMALL_STATE(54)] = 933,
  [SMALL_STATE(55)] = 954,
  [SMALL_STATE(56)] = 973,
  [SMALL_STATE(57)] = 999,
  [SMALL_STATE(58)] = 1025,
  [SMALL_STATE(59)] = 1045,
  [SMALL_STATE(60)] = 1065,
  [SMALL_STATE(61)] = 1085,
  [SMALL_STATE(62)] = 1105,
  [SMALL_STATE(63)] = 1125,
  [SMALL_STATE(64)] = 1145,
  [SMALL_STATE(65)] = 1165,
  [SMALL_STATE(66)] = 1185,
  [SMALL_STATE(67)] = 1205,
  [SMALL_STATE(68)] = 1225,
  [SMALL_STATE(69)] = 1245,
  [SMALL_STATE(70)] = 1265,
  [SMALL_STATE(71)] = 1285,
  [SMALL_STATE(72)] = 1305,
  [SMALL_STATE(73)] = 1325,
  [SMALL_STATE(74)] = 1345,
  [SMALL_STATE(75)] = 1365,
  [SMALL_STATE(76)] = 1385,
  [SMALL_STATE(77)] = 1405,
  [SMALL_STATE(78)] = 1425,
  [SMALL_STATE(79)] = 1445,
  [SMALL_STATE(80)] = 1465,
  [SMALL_STATE(81)] = 1487,
  [SMALL_STATE(82)] = 1509,
  [SMALL_STATE(83)] = 1531,
  [SMALL_STATE(84)] = 1553,
  [SMALL_STATE(85)] = 1572,
  [SMALL_STATE(86)] = 1591,
  [SMALL_STATE(87)] = 1610,
  [SMALL_STATE(88)] = 1629,
  [SMALL_STATE(89)] = 1648,
  [SMALL_STATE(90)] = 1667,
  [SMALL_STATE(91)] = 1679,
  [SMALL_STATE(92)] = 1693,
  [SMALL_STATE(93)] = 1706,
  [SMALL_STATE(94)] = 1715,
  [SMALL_STATE(95)] = 1728,
  [SMALL_STATE(96)] = 1741,
  [SMALL_STATE(97)] = 1754,
  [SMALL_STATE(98)] = 1765,
  [SMALL_STATE(99)] = 1774,
  [SMALL_STATE(100)] = 1783,
  [SMALL_STATE(101)] = 1792,
  [SMALL_STATE(102)] = 1801,
  [SMALL_STATE(103)] = 1812,
  [SMALL_STATE(104)] = 1821,
  [SMALL_STATE(105)] = 1827,
  [SMALL_STATE(106)] = 1833,
  [SMALL_STATE(107)] = 1841,
  [SMALL_STATE(108)] = 1849,
  [SMALL_STATE(109)] = 1855,
  [SMALL_STATE(110)] = 1861,
  [SMALL_STATE(111)] = 1867,
  [SMALL_STATE(112)] = 1874,
  [SMALL_STATE(113)] = 1881,
  [SMALL_STATE(114)] = 1886,
  [SMALL_STATE(115)] = 1891,
  [SMALL_STATE(116)] = 1898,
  [SMALL_STATE(117)] = 1905,
  [SMALL_STATE(118)] = 1910,
  [SMALL_STATE(119)] = 1915,
  [SMALL_STATE(120)] = 1920,
  [SMALL_STATE(121)] = 1925,
  [SMALL_STATE(122)] = 1932,
  [SMALL_STATE(123)] = 1937,
  [SMALL_STATE(124)] = 1944,
  [SMALL_STATE(125)] = 1951,
  [SMALL_STATE(126)] = 1956,
  [SMALL_STATE(127)] = 1963,
  [SMALL_STATE(128)] = 1970,
  [SMALL_STATE(129)] = 1975,
  [SMALL_STATE(130)] = 1980,
  [SMALL_STATE(131)] = 1985,
  [SMALL_STATE(132)] = 1990,
  [SMALL_STATE(133)] = 1995,
  [SMALL_STATE(134)] = 2002,
  [SMALL_STATE(135)] = 2009,
  [SMALL_STATE(136)] = 2016,
  [SMALL_STATE(137)] = 2021,
  [SMALL_STATE(138)] = 2028,
  [SMALL_STATE(139)] = 2035,
  [SMALL_STATE(140)] = 2040,
  [SMALL_STATE(141)] = 2047,
  [SMALL_STATE(142)] = 2054,
  [SMALL_STATE(143)] = 2061,
  [SMALL_STATE(144)] = 2065,
  [SMALL_STATE(145)] = 2069,
  [SMALL_STATE(146)] = 2073,
  [SMALL_STATE(147)] = 2077,
  [SMALL_STATE(148)] = 2081,
  [SMALL_STATE(149)] = 2085,
  [SMALL_STATE(150)] = 2089,
  [SMALL_STATE(151)] = 2093,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(31),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(82),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(81),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(53),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(34),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(34),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(35),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(53),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(27),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(131),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(129),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(123),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(126),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(121),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arrow_call, 3, .production_id = 4),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arrow_call, 3, .production_id = 4),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_call, 2, .production_id = 1),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn_call, 2, .production_id = 1),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 1),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 1),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tup, 1),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tup, 1),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__fn_body, 2),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__fn_body, 2),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 4, .production_id = 7),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 4, .production_id = 7),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 4, .production_id = 8),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 4, .production_id = 8),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 3, .production_id = 3),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 3, .production_id = 3),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pu, 5, .production_id = 11),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pu, 5, .production_id = 11),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pu, 3, .production_id = 3),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pu, 3, .production_id = 3),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 5, .production_id = 11),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 5, .production_id = 11),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__tup_params, 3),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__tup_params, 3),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pu, 4, .production_id = 7),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pu, 4, .production_id = 7),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pu, 4, .production_id = 8),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pu, 4, .production_id = 8),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_t_pu, 4, .production_id = 12),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_t_pu, 4, .production_id = 12),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_t_pu, 3, .production_id = 9),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_t_pu, 3, .production_id = 9),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_t_fn, 3, .production_id = 9),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_t_fn, 3, .production_id = 9),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_declaration, 5, .production_id = 10),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_const_declaration, 5, .production_id = 10),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_declaration, 4, .production_id = 5),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_const_declaration, 4, .production_id = 5),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mut_declaration, 4, .production_id = 5),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mut_declaration, 4, .production_id = 5),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inner_statement, 1),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__inner_statement, 1),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mut_declaration, 5, .production_id = 10),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mut_declaration, 5, .production_id = 10),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_t_fn, 4, .production_id = 12),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_t_fn, 4, .production_id = 12),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [288] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [294] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [298] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [302] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [306] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [324] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 1, .production_id = 2),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 1, .production_id = 2),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [332] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_parameters_repeat1, 1),
  [334] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 1),
  [336] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2),
  [338] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameters, 2),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [342] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 1),
  [344] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameters, 1),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [348] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2), SHIFT_REPEAT(101),
  [351] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2), SHIFT_REPEAT(97),
  [354] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 3, .production_id = 6),
  [356] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, .production_id = 6),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [394] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [406] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [410] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_sylt(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
