#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 132
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 11

enum {
  sym_identifier = 1,
  sym_t_void = 2,
  sym_t_bool = 3,
  sym_t_int = 4,
  sym_t_float = 5,
  sym_t_str = 6,
  anon_sym_COLON = 7,
  anon_sym_COMMA = 8,
  anon_sym_fn = 9,
  anon_sym_DASH_GT = 10,
  anon_sym_pu = 11,
  anon_sym_EQ = 12,
  sym_int = 13,
  aux_sym_float_token1 = 14,
  aux_sym_float_token2 = 15,
  aux_sym_float_token3 = 16,
  sym_nil = 17,
  anon_sym_true = 18,
  anon_sym_false = 19,
  sym_str = 20,
  anon_sym_end = 21,
  anon_sym_do = 22,
  sym_source_file = 23,
  sym__type_primitive = 24,
  sym_parameter = 25,
  sym_parameters = 26,
  sym_t_fn = 27,
  sym_t_pu = 28,
  sym__type = 29,
  sym__inner_statement = 30,
  sym__outer_statement = 31,
  sym__declaration = 32,
  sym_const_declaration = 33,
  sym_mut_declaration = 34,
  sym_float = 35,
  sym_bool = 36,
  sym__fn_body = 37,
  sym_fn = 38,
  sym_pu = 39,
  sym__expression = 40,
  aux_sym_source_file_repeat1 = 41,
  aux_sym_parameters_repeat1 = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_t_void] = "t_void",
  [sym_t_bool] = "t_bool",
  [sym_t_int] = "t_int",
  [sym_t_float] = "t_float",
  [sym_t_str] = "t_str",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_fn] = "fn",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_pu] = "pu",
  [anon_sym_EQ] = "=",
  [sym_int] = "int",
  [aux_sym_float_token1] = "float_token1",
  [aux_sym_float_token2] = "float_token2",
  [aux_sym_float_token3] = "float_token3",
  [sym_nil] = "nil",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_str] = "str",
  [anon_sym_end] = "end",
  [anon_sym_do] = "do",
  [sym_source_file] = "source_file",
  [sym__type_primitive] = "_type_primitive",
  [sym_parameter] = "parameter",
  [sym_parameters] = "parameters",
  [sym_t_fn] = "t_fn",
  [sym_t_pu] = "t_pu",
  [sym__type] = "_type",
  [sym__inner_statement] = "_inner_statement",
  [sym__outer_statement] = "_outer_statement",
  [sym__declaration] = "_declaration",
  [sym_const_declaration] = "const_declaration",
  [sym_mut_declaration] = "mut_declaration",
  [sym_float] = "float",
  [sym_bool] = "bool",
  [sym__fn_body] = "_fn_body",
  [sym_fn] = "fn",
  [sym_pu] = "pu",
  [sym__expression] = "_expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_t_void] = sym_t_void,
  [sym_t_bool] = sym_t_bool,
  [sym_t_int] = sym_t_int,
  [sym_t_float] = sym_t_float,
  [sym_t_str] = sym_t_str,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_pu] = anon_sym_pu,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_int] = sym_int,
  [aux_sym_float_token1] = aux_sym_float_token1,
  [aux_sym_float_token2] = aux_sym_float_token2,
  [aux_sym_float_token3] = aux_sym_float_token3,
  [sym_nil] = sym_nil,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_str] = sym_str,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_do] = anon_sym_do,
  [sym_source_file] = sym_source_file,
  [sym__type_primitive] = sym__type_primitive,
  [sym_parameter] = sym_parameter,
  [sym_parameters] = sym_parameters,
  [sym_t_fn] = sym_t_fn,
  [sym_t_pu] = sym_t_pu,
  [sym__type] = sym__type,
  [sym__inner_statement] = sym__inner_statement,
  [sym__outer_statement] = sym__outer_statement,
  [sym__declaration] = sym__declaration,
  [sym_const_declaration] = sym_const_declaration,
  [sym_mut_declaration] = sym_mut_declaration,
  [sym_float] = sym_float,
  [sym_bool] = sym_bool,
  [sym__fn_body] = sym__fn_body,
  [sym_fn] = sym_fn,
  [sym_pu] = sym_pu,
  [sym__expression] = sym__expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_t_void] = {
    .visible = true,
    .named = true,
  },
  [sym_t_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_t_int] = {
    .visible = true,
    .named = true,
  },
  [sym_t_float] = {
    .visible = true,
    .named = true,
  },
  [sym_t_str] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pu] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_float_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_float_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_float_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_nil] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_str] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__type_primitive] = {
    .visible = false,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_t_fn] = {
    .visible = true,
    .named = true,
  },
  [sym_t_pu] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym__inner_statement] = {
    .visible = false,
    .named = true,
  },
  [sym__outer_statement] = {
    .visible = false,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_const_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_mut_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym__fn_body] = {
    .visible = false,
    .named = true,
  },
  [sym_fn] = {
    .visible = true,
    .named = true,
  },
  [sym_pu] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_body = 1,
  field_expression = 2,
  field_name = 3,
  field_parameters = 4,
  field_return = 5,
  field_type = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_expression] = "expression",
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_return] = "return",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 3},
  [5] = {.index = 7, .length = 3},
  [6] = {.index = 10, .length = 1},
  [7] = {.index = 11, .length = 1},
  [8] = {.index = 12, .length = 3},
  [9] = {.index = 15, .length = 3},
  [10] = {.index = 18, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_body, 2},
  [2] =
    {field_expression, 3},
    {field_name, 0},
  [4] =
    {field_name, 0},
    {field_type, 1},
    {field_type, 2},
  [7] =
    {field_body, 3},
    {field_return, 1},
    {field_return, 2},
  [10] =
    {field_body, 3},
  [11] =
    {field_return, 2},
  [12] =
    {field_expression, 4},
    {field_name, 0},
    {field_type, 2},
  [15] =
    {field_body, 4},
    {field_return, 2},
    {field_return, 3},
  [18] =
    {field_parameters, 1},
    {field_return, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(35);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == ',') ADVANCE(45);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == ':') ADVANCE(44);
      if (lookahead == '=') ADVANCE(50);
      if (lookahead == 'b') ADVANCE(22);
      if (lookahead == 'd') ADVANCE(18);
      if (lookahead == 'e') ADVANCE(16);
      if (lookahead == 'f') ADVANCE(5);
      if (lookahead == 'i') ADVANCE(17);
      if (lookahead == 'n') ADVANCE(12);
      if (lookahead == 'p') ADVANCE(29);
      if (lookahead == 's') ADVANCE(28);
      if (lookahead == 't') ADVANCE(24);
      if (lookahead == 'v') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(58);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == ',') ADVANCE(45);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == ':') ADVANCE(44);
      if (lookahead == 'd') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 3:
      if (lookahead == ',') ADVANCE(45);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == ':') ADVANCE(44);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(48);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(13);
      if (lookahead == 'l') ADVANCE(19);
      if (lookahead == 'n') ADVANCE(46);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 7:
      if (lookahead == 'd') ADVANCE(59);
      END_STATE();
    case 8:
      if (lookahead == 'd') ADVANCE(39);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(56);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(14);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(55);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(40);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(60);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(6);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 25:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 29:
      if (lookahead == 'u') ADVANCE(49);
      END_STATE();
    case 30:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 31:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 34:
      if (eof) ADVANCE(35);
      if (lookahead == ':') ADVANCE(44);
      if (lookahead == '=') ADVANCE(50);
      if (lookahead == 'f') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(34)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_t_void);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_t_bool);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_t_int);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_t_float);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_t_str);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_pu);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_int);
      if (lookahead == '.') ADVANCE(52);
      if (lookahead == 'e') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_float_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_float_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_float_token3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_nil);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_str);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_do);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_do);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 34},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 34},
  [35] = {.lex_state = 34},
  [36] = {.lex_state = 34},
  [37] = {.lex_state = 34},
  [38] = {.lex_state = 34},
  [39] = {.lex_state = 34},
  [40] = {.lex_state = 34},
  [41] = {.lex_state = 34},
  [42] = {.lex_state = 34},
  [43] = {.lex_state = 34},
  [44] = {.lex_state = 34},
  [45] = {.lex_state = 34},
  [46] = {.lex_state = 34},
  [47] = {.lex_state = 34},
  [48] = {.lex_state = 34},
  [49] = {.lex_state = 34},
  [50] = {.lex_state = 34},
  [51] = {.lex_state = 34},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 34},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 34},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 34},
  [72] = {.lex_state = 2},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 34},
  [77] = {.lex_state = 3},
  [78] = {.lex_state = 3},
  [79] = {.lex_state = 34},
  [80] = {.lex_state = 34},
  [81] = {.lex_state = 34},
  [82] = {.lex_state = 3},
  [83] = {.lex_state = 34},
  [84] = {.lex_state = 34},
  [85] = {.lex_state = 34},
  [86] = {.lex_state = 34},
  [87] = {.lex_state = 34},
  [88] = {.lex_state = 34},
  [89] = {.lex_state = 34},
  [90] = {.lex_state = 34},
  [91] = {.lex_state = 34},
  [92] = {.lex_state = 34},
  [93] = {.lex_state = 3},
  [94] = {.lex_state = 3},
  [95] = {.lex_state = 3},
  [96] = {.lex_state = 34},
  [97] = {.lex_state = 3},
  [98] = {.lex_state = 34},
  [99] = {.lex_state = 3},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_t_void] = ACTIONS(1),
    [sym_t_bool] = ACTIONS(1),
    [sym_t_int] = ACTIONS(1),
    [sym_t_float] = ACTIONS(1),
    [sym_t_str] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_pu] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [aux_sym_float_token1] = ACTIONS(1),
    [aux_sym_float_token2] = ACTIONS(1),
    [aux_sym_float_token3] = ACTIONS(1),
    [sym_nil] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_str] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(130),
    [sym__inner_statement] = STATE(34),
    [sym__outer_statement] = STATE(34),
    [sym__declaration] = STATE(34),
    [sym_const_declaration] = STATE(34),
    [sym_mut_declaration] = STATE(34),
    [sym_fn] = STATE(34),
    [aux_sym_source_file_repeat1] = STATE(34),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(11), 1,
      anon_sym_pu,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(17), 1,
      aux_sym_float_token2,
    ACTIONS(15), 2,
      aux_sym_float_token1,
      aux_sym_float_token3,
    ACTIONS(19), 2,
      sym_nil,
      sym_str,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(127), 5,
      sym_float,
      sym_bool,
      sym_fn,
      sym_pu,
      sym__expression,
  [32] = 8,
    ACTIONS(23), 1,
      anon_sym_fn,
    ACTIONS(25), 1,
      anon_sym_pu,
    ACTIONS(27), 1,
      sym_int,
    ACTIONS(31), 1,
      aux_sym_float_token2,
    ACTIONS(29), 2,
      aux_sym_float_token1,
      aux_sym_float_token3,
    ACTIONS(33), 2,
      sym_nil,
      sym_str,
    ACTIONS(35), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(98), 5,
      sym_float,
      sym_bool,
      sym_fn,
      sym_pu,
      sym__expression,
  [64] = 8,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(11), 1,
      anon_sym_pu,
    ACTIONS(17), 1,
      aux_sym_float_token2,
    ACTIONS(37), 1,
      sym_int,
    ACTIONS(15), 2,
      aux_sym_float_token1,
      aux_sym_float_token3,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(39), 2,
      sym_nil,
      sym_str,
    STATE(128), 5,
      sym_float,
      sym_bool,
      sym_fn,
      sym_pu,
      sym__expression,
  [96] = 8,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(11), 1,
      anon_sym_pu,
    ACTIONS(17), 1,
      aux_sym_float_token2,
    ACTIONS(41), 1,
      sym_int,
    ACTIONS(15), 2,
      aux_sym_float_token1,
      aux_sym_float_token3,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(43), 2,
      sym_nil,
      sym_str,
    STATE(107), 5,
      sym_float,
      sym_bool,
      sym_fn,
      sym_pu,
      sym__expression,
  [128] = 8,
    ACTIONS(23), 1,
      anon_sym_fn,
    ACTIONS(25), 1,
      anon_sym_pu,
    ACTIONS(31), 1,
      aux_sym_float_token2,
    ACTIONS(45), 1,
      sym_int,
    ACTIONS(29), 2,
      aux_sym_float_token1,
      aux_sym_float_token3,
    ACTIONS(35), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(47), 2,
      sym_nil,
      sym_str,
    STATE(89), 5,
      sym_float,
      sym_bool,
      sym_fn,
      sym_pu,
      sym__expression,
  [160] = 8,
    ACTIONS(23), 1,
      anon_sym_fn,
    ACTIONS(25), 1,
      anon_sym_pu,
    ACTIONS(31), 1,
      aux_sym_float_token2,
    ACTIONS(49), 1,
      sym_int,
    ACTIONS(29), 2,
      aux_sym_float_token1,
      aux_sym_float_token3,
    ACTIONS(35), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(51), 2,
      sym_nil,
      sym_str,
    STATE(96), 5,
      sym_float,
      sym_bool,
      sym_fn,
      sym_pu,
      sym__expression,
  [192] = 8,
    ACTIONS(23), 1,
      anon_sym_fn,
    ACTIONS(25), 1,
      anon_sym_pu,
    ACTIONS(31), 1,
      aux_sym_float_token2,
    ACTIONS(53), 1,
      sym_int,
    ACTIONS(29), 2,
      aux_sym_float_token1,
      aux_sym_float_token3,
    ACTIONS(35), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(55), 2,
      sym_nil,
      sym_str,
    STATE(88), 5,
      sym_float,
      sym_bool,
      sym_fn,
      sym_pu,
      sym__expression,
  [224] = 8,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(11), 1,
      anon_sym_pu,
    ACTIONS(17), 1,
      aux_sym_float_token2,
    ACTIONS(57), 1,
      sym_int,
    ACTIONS(15), 2,
      aux_sym_float_token1,
      aux_sym_float_token3,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(59), 2,
      sym_nil,
      sym_str,
    STATE(125), 5,
      sym_float,
      sym_bool,
      sym_fn,
      sym_pu,
      sym__expression,
  [256] = 6,
    ACTIONS(63), 1,
      anon_sym_COLON,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(67), 1,
      anon_sym_pu,
    ACTIONS(69), 1,
      anon_sym_EQ,
    STATE(103), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(61), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [282] = 6,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(67), 1,
      anon_sym_pu,
    ACTIONS(73), 1,
      anon_sym_COLON,
    ACTIONS(75), 1,
      anon_sym_EQ,
    STATE(101), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(71), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [308] = 4,
    ACTIONS(79), 1,
      anon_sym_fn,
    ACTIONS(81), 1,
      anon_sym_pu,
    STATE(75), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(77), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [328] = 4,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(67), 1,
      anon_sym_pu,
    STATE(41), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(83), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [348] = 4,
    ACTIONS(79), 1,
      anon_sym_fn,
    ACTIONS(81), 1,
      anon_sym_pu,
    STATE(74), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(85), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [368] = 4,
    ACTIONS(89), 1,
      anon_sym_fn,
    ACTIONS(91), 1,
      anon_sym_pu,
    STATE(78), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(87), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [388] = 4,
    ACTIONS(79), 1,
      anon_sym_fn,
    ACTIONS(81), 1,
      anon_sym_pu,
    STATE(72), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(93), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [408] = 4,
    ACTIONS(79), 1,
      anon_sym_fn,
    ACTIONS(81), 1,
      anon_sym_pu,
    STATE(70), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(95), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [428] = 4,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(67), 1,
      anon_sym_pu,
    STATE(40), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(97), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [448] = 4,
    ACTIONS(79), 1,
      anon_sym_fn,
    ACTIONS(81), 1,
      anon_sym_pu,
    STATE(64), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(99), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [468] = 4,
    ACTIONS(89), 1,
      anon_sym_fn,
    ACTIONS(91), 1,
      anon_sym_pu,
    STATE(94), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(101), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [488] = 4,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(67), 1,
      anon_sym_pu,
    STATE(44), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(103), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [508] = 4,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(67), 1,
      anon_sym_pu,
    STATE(45), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(105), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [528] = 4,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(67), 1,
      anon_sym_pu,
    STATE(47), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(107), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [548] = 4,
    ACTIONS(89), 1,
      anon_sym_fn,
    ACTIONS(91), 1,
      anon_sym_pu,
    STATE(95), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(109), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [568] = 4,
    ACTIONS(89), 1,
      anon_sym_fn,
    ACTIONS(91), 1,
      anon_sym_pu,
    STATE(97), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(111), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [588] = 4,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(67), 1,
      anon_sym_pu,
    STATE(51), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(113), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [608] = 4,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(67), 1,
      anon_sym_pu,
    STATE(38), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(115), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [628] = 4,
    ACTIONS(89), 1,
      anon_sym_fn,
    ACTIONS(91), 1,
      anon_sym_pu,
    STATE(93), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(117), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [648] = 4,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(67), 1,
      anon_sym_pu,
    STATE(68), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(119), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [668] = 4,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(67), 1,
      anon_sym_pu,
    STATE(65), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(121), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [688] = 4,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(67), 1,
      anon_sym_pu,
    STATE(76), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(123), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [708] = 4,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(67), 1,
      anon_sym_pu,
    STATE(50), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(125), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [728] = 4,
    ACTIONS(65), 1,
      anon_sym_fn,
    ACTIONS(67), 1,
      anon_sym_pu,
    STATE(71), 4,
      sym__type_primitive,
      sym_t_fn,
      sym_t_pu,
      sym__type,
    ACTIONS(127), 5,
      sym_t_void,
      sym_t_bool,
      sym_t_int,
      sym_t_float,
      sym_t_str,
  [748] = 4,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(129), 1,
      ts_builtin_sym_end,
    STATE(35), 7,
      sym__inner_statement,
      sym__outer_statement,
      sym__declaration,
      sym_const_declaration,
      sym_mut_declaration,
      sym_fn,
      aux_sym_source_file_repeat1,
  [767] = 4,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    ACTIONS(133), 1,
      sym_identifier,
    ACTIONS(136), 1,
      anon_sym_fn,
    STATE(35), 7,
      sym__inner_statement,
      sym__outer_statement,
      sym__declaration,
      sym_const_declaration,
      sym_mut_declaration,
      sym_fn,
      aux_sym_source_file_repeat1,
  [786] = 4,
    ACTIONS(139), 1,
      sym_identifier,
    ACTIONS(141), 1,
      anon_sym_fn,
    STATE(123), 1,
      sym__fn_body,
    STATE(109), 5,
      sym__inner_statement,
      sym__declaration,
      sym_const_declaration,
      sym_mut_declaration,
      sym_fn,
  [803] = 4,
    ACTIONS(139), 1,
      sym_identifier,
    ACTIONS(141), 1,
      anon_sym_fn,
    STATE(84), 1,
      sym__fn_body,
    STATE(126), 5,
      sym__inner_statement,
      sym__declaration,
      sym_const_declaration,
      sym_mut_declaration,
      sym_fn,
  [820] = 4,
    ACTIONS(139), 1,
      sym_identifier,
    ACTIONS(141), 1,
      anon_sym_fn,
    STATE(116), 1,
      sym__fn_body,
    STATE(109), 5,
      sym__inner_statement,
      sym__declaration,
      sym_const_declaration,
      sym_mut_declaration,
      sym_fn,
  [837] = 4,
    ACTIONS(139), 1,
      sym_identifier,
    ACTIONS(141), 1,
      anon_sym_fn,
    STATE(85), 1,
      sym__fn_body,
    STATE(126), 5,
      sym__inner_statement,
      sym__declaration,
      sym_const_declaration,
      sym_mut_declaration,
      sym_fn,
  [854] = 4,
    ACTIONS(139), 1,
      sym_identifier,
    ACTIONS(141), 1,
      anon_sym_fn,
    STATE(124), 1,
      sym__fn_body,
    STATE(109), 5,
      sym__inner_statement,
      sym__declaration,
      sym_const_declaration,
      sym_mut_declaration,
      sym_fn,
  [871] = 4,
    ACTIONS(139), 1,
      sym_identifier,
    ACTIONS(141), 1,
      anon_sym_fn,
    STATE(80), 1,
      sym__fn_body,
    STATE(126), 5,
      sym__inner_statement,
      sym__declaration,
      sym_const_declaration,
      sym_mut_declaration,
      sym_fn,
  [888] = 4,
    ACTIONS(139), 1,
      sym_identifier,
    ACTIONS(141), 1,
      anon_sym_fn,
    STATE(115), 1,
      sym__fn_body,
    STATE(109), 5,
      sym__inner_statement,
      sym__declaration,
      sym_const_declaration,
      sym_mut_declaration,
      sym_fn,
  [905] = 4,
    ACTIONS(139), 1,
      sym_identifier,
    ACTIONS(141), 1,
      anon_sym_fn,
    STATE(81), 1,
      sym__fn_body,
    STATE(126), 5,
      sym__inner_statement,
      sym__declaration,
      sym_const_declaration,
      sym_mut_declaration,
      sym_fn,
  [922] = 4,
    ACTIONS(139), 1,
      sym_identifier,
    ACTIONS(141), 1,
      anon_sym_fn,
    STATE(113), 1,
      sym__fn_body,
    STATE(109), 5,
      sym__inner_statement,
      sym__declaration,
      sym_const_declaration,
      sym_mut_declaration,
      sym_fn,
  [939] = 4,
    ACTIONS(139), 1,
      sym_identifier,
    ACTIONS(141), 1,
      anon_sym_fn,
    STATE(114), 1,
      sym__fn_body,
    STATE(109), 5,
      sym__inner_statement,
      sym__declaration,
      sym_const_declaration,
      sym_mut_declaration,
      sym_fn,
  [956] = 4,
    ACTIONS(139), 1,
      sym_identifier,
    ACTIONS(141), 1,
      anon_sym_fn,
    STATE(106), 1,
      sym__fn_body,
    STATE(109), 5,
      sym__inner_statement,
      sym__declaration,
      sym_const_declaration,
      sym_mut_declaration,
      sym_fn,
  [973] = 4,
    ACTIONS(139), 1,
      sym_identifier,
    ACTIONS(141), 1,
      anon_sym_fn,
    STATE(90), 1,
      sym__fn_body,
    STATE(126), 5,
      sym__inner_statement,
      sym__declaration,
      sym_const_declaration,
      sym_mut_declaration,
      sym_fn,
  [990] = 4,
    ACTIONS(139), 1,
      sym_identifier,
    ACTIONS(141), 1,
      anon_sym_fn,
    STATE(92), 1,
      sym__fn_body,
    STATE(126), 5,
      sym__inner_statement,
      sym__declaration,
      sym_const_declaration,
      sym_mut_declaration,
      sym_fn,
  [1007] = 4,
    ACTIONS(139), 1,
      sym_identifier,
    ACTIONS(141), 1,
      anon_sym_fn,
    STATE(129), 1,
      sym__fn_body,
    STATE(109), 5,
      sym__inner_statement,
      sym__declaration,
      sym_const_declaration,
      sym_mut_declaration,
      sym_fn,
  [1024] = 4,
    ACTIONS(139), 1,
      sym_identifier,
    ACTIONS(141), 1,
      anon_sym_fn,
    STATE(83), 1,
      sym__fn_body,
    STATE(126), 5,
      sym__inner_statement,
      sym__declaration,
      sym_const_declaration,
      sym_mut_declaration,
      sym_fn,
  [1041] = 4,
    ACTIONS(139), 1,
      sym_identifier,
    ACTIONS(141), 1,
      anon_sym_fn,
    STATE(91), 1,
      sym__fn_body,
    STATE(126), 5,
      sym__inner_statement,
      sym__declaration,
      sym_const_declaration,
      sym_mut_declaration,
      sym_fn,
  [1058] = 7,
    ACTIONS(143), 1,
      sym_identifier,
    ACTIONS(145), 1,
      anon_sym_COMMA,
    ACTIONS(147), 1,
      anon_sym_DASH_GT,
    ACTIONS(149), 1,
      anon_sym_do,
    STATE(69), 1,
      aux_sym_parameters_repeat1,
    STATE(73), 1,
      sym_parameter,
    STATE(104), 1,
      sym_parameters,
  [1080] = 7,
    ACTIONS(143), 1,
      sym_identifier,
    ACTIONS(145), 1,
      anon_sym_COMMA,
    ACTIONS(151), 1,
      anon_sym_DASH_GT,
    ACTIONS(153), 1,
      anon_sym_do,
    STATE(69), 1,
      aux_sym_parameters_repeat1,
    STATE(73), 1,
      sym_parameter,
    STATE(105), 1,
      sym_parameters,
  [1102] = 7,
    ACTIONS(143), 1,
      sym_identifier,
    ACTIONS(145), 1,
      anon_sym_COMMA,
    ACTIONS(155), 1,
      anon_sym_DASH_GT,
    ACTIONS(157), 1,
      anon_sym_do,
    STATE(69), 1,
      aux_sym_parameters_repeat1,
    STATE(73), 1,
      sym_parameter,
    STATE(102), 1,
      sym_parameters,
  [1124] = 7,
    ACTIONS(143), 1,
      sym_identifier,
    ACTIONS(145), 1,
      anon_sym_COMMA,
    ACTIONS(159), 1,
      anon_sym_DASH_GT,
    ACTIONS(161), 1,
      anon_sym_do,
    STATE(69), 1,
      aux_sym_parameters_repeat1,
    STATE(73), 1,
      sym_parameter,
    STATE(100), 1,
      sym_parameters,
  [1146] = 6,
    ACTIONS(163), 1,
      sym_identifier,
    ACTIONS(165), 1,
      anon_sym_COMMA,
    ACTIONS(167), 1,
      anon_sym_DASH_GT,
    STATE(67), 1,
      aux_sym_parameters_repeat1,
    STATE(99), 1,
      sym_parameter,
    STATE(117), 1,
      sym_parameters,
  [1165] = 6,
    ACTIONS(163), 1,
      sym_identifier,
    ACTIONS(165), 1,
      anon_sym_COMMA,
    ACTIONS(169), 1,
      anon_sym_DASH_GT,
    STATE(67), 1,
      aux_sym_parameters_repeat1,
    STATE(99), 1,
      sym_parameter,
    STATE(121), 1,
      sym_parameters,
  [1184] = 6,
    ACTIONS(163), 1,
      sym_identifier,
    ACTIONS(165), 1,
      anon_sym_COMMA,
    ACTIONS(171), 1,
      anon_sym_DASH_GT,
    STATE(67), 1,
      aux_sym_parameters_repeat1,
    STATE(99), 1,
      sym_parameter,
    STATE(118), 1,
      sym_parameters,
  [1203] = 6,
    ACTIONS(163), 1,
      sym_identifier,
    ACTIONS(165), 1,
      anon_sym_COMMA,
    ACTIONS(173), 1,
      anon_sym_DASH_GT,
    STATE(67), 1,
      aux_sym_parameters_repeat1,
    STATE(99), 1,
      sym_parameter,
    STATE(112), 1,
      sym_parameters,
  [1222] = 6,
    ACTIONS(163), 1,
      sym_identifier,
    ACTIONS(165), 1,
      anon_sym_COMMA,
    ACTIONS(175), 1,
      anon_sym_DASH_GT,
    STATE(67), 1,
      aux_sym_parameters_repeat1,
    STATE(99), 1,
      sym_parameter,
    STATE(111), 1,
      sym_parameters,
  [1241] = 6,
    ACTIONS(163), 1,
      sym_identifier,
    ACTIONS(165), 1,
      anon_sym_COMMA,
    ACTIONS(177), 1,
      anon_sym_DASH_GT,
    STATE(67), 1,
      aux_sym_parameters_repeat1,
    STATE(99), 1,
      sym_parameter,
    STATE(120), 1,
      sym_parameters,
  [1260] = 3,
    ACTIONS(181), 1,
      anon_sym_COLON,
    ACTIONS(179), 2,
      sym_identifier,
      anon_sym_do,
    ACTIONS(183), 2,
      anon_sym_COMMA,
      anon_sym_DASH_GT,
  [1272] = 4,
    ACTIONS(185), 1,
      sym_identifier,
    ACTIONS(187), 1,
      anon_sym_COMMA,
    ACTIONS(189), 1,
      anon_sym_DASH_GT,
    ACTIONS(191), 1,
      anon_sym_do,
  [1285] = 2,
    ACTIONS(193), 2,
      sym_identifier,
      anon_sym_do,
    ACTIONS(195), 2,
      anon_sym_COMMA,
      anon_sym_DASH_GT,
  [1294] = 2,
    ACTIONS(197), 2,
      sym_identifier,
      anon_sym_fn,
    ACTIONS(199), 2,
      anon_sym_COLON,
      anon_sym_EQ,
  [1303] = 2,
    ACTIONS(201), 1,
      anon_sym_COLON,
    ACTIONS(183), 3,
      sym_identifier,
      anon_sym_COMMA,
      anon_sym_DASH_GT,
  [1312] = 4,
    ACTIONS(163), 1,
      sym_identifier,
    ACTIONS(203), 1,
      anon_sym_COMMA,
    STATE(77), 1,
      aux_sym_parameters_repeat1,
    STATE(82), 1,
      sym_parameter,
  [1325] = 2,
    ACTIONS(205), 2,
      sym_identifier,
      anon_sym_fn,
    ACTIONS(207), 2,
      anon_sym_COLON,
      anon_sym_EQ,
  [1334] = 4,
    ACTIONS(203), 1,
      anon_sym_COMMA,
    ACTIONS(209), 1,
      sym_identifier,
    STATE(63), 1,
      sym_parameter,
    STATE(77), 1,
      aux_sym_parameters_repeat1,
  [1347] = 2,
    ACTIONS(211), 2,
      sym_identifier,
      anon_sym_do,
    ACTIONS(213), 2,
      anon_sym_COMMA,
      anon_sym_DASH_GT,
  [1356] = 2,
    ACTIONS(215), 2,
      sym_identifier,
      anon_sym_fn,
    ACTIONS(217), 2,
      anon_sym_COLON,
      anon_sym_EQ,
  [1365] = 2,
    ACTIONS(215), 2,
      sym_identifier,
      anon_sym_do,
    ACTIONS(217), 2,
      anon_sym_COMMA,
      anon_sym_DASH_GT,
  [1374] = 4,
    ACTIONS(185), 1,
      sym_identifier,
    ACTIONS(187), 1,
      anon_sym_COMMA,
    ACTIONS(219), 1,
      anon_sym_DASH_GT,
    ACTIONS(221), 1,
      anon_sym_do,
  [1387] = 2,
    ACTIONS(197), 2,
      sym_identifier,
      anon_sym_do,
    ACTIONS(199), 2,
      anon_sym_COMMA,
      anon_sym_DASH_GT,
  [1396] = 2,
    ACTIONS(205), 2,
      sym_identifier,
      anon_sym_do,
    ACTIONS(207), 2,
      anon_sym_COMMA,
      anon_sym_DASH_GT,
  [1405] = 2,
    ACTIONS(211), 2,
      sym_identifier,
      anon_sym_fn,
    ACTIONS(213), 2,
      anon_sym_COLON,
      anon_sym_EQ,
  [1414] = 3,
    ACTIONS(223), 1,
      sym_identifier,
    ACTIONS(226), 1,
      anon_sym_COMMA,
    STATE(77), 2,
      sym_parameter,
      aux_sym_parameters_repeat1,
  [1425] = 1,
    ACTIONS(199), 3,
      sym_identifier,
      anon_sym_COMMA,
      anon_sym_DASH_GT,
  [1431] = 2,
    ACTIONS(229), 1,
      ts_builtin_sym_end,
    ACTIONS(231), 2,
      sym_identifier,
      anon_sym_fn,
  [1439] = 2,
    ACTIONS(233), 1,
      ts_builtin_sym_end,
    ACTIONS(235), 2,
      sym_identifier,
      anon_sym_fn,
  [1447] = 2,
    ACTIONS(237), 1,
      ts_builtin_sym_end,
    ACTIONS(239), 2,
      sym_identifier,
      anon_sym_fn,
  [1455] = 2,
    ACTIONS(189), 1,
      anon_sym_DASH_GT,
    ACTIONS(187), 2,
      sym_identifier,
      anon_sym_COMMA,
  [1463] = 2,
    ACTIONS(241), 1,
      ts_builtin_sym_end,
    ACTIONS(243), 2,
      sym_identifier,
      anon_sym_fn,
  [1471] = 2,
    ACTIONS(245), 1,
      ts_builtin_sym_end,
    ACTIONS(247), 2,
      sym_identifier,
      anon_sym_fn,
  [1479] = 2,
    ACTIONS(249), 1,
      ts_builtin_sym_end,
    ACTIONS(251), 2,
      sym_identifier,
      anon_sym_fn,
  [1487] = 2,
    ACTIONS(253), 1,
      ts_builtin_sym_end,
    ACTIONS(255), 2,
      sym_identifier,
      anon_sym_fn,
  [1495] = 2,
    ACTIONS(257), 1,
      ts_builtin_sym_end,
    ACTIONS(259), 2,
      sym_identifier,
      anon_sym_fn,
  [1503] = 2,
    ACTIONS(261), 1,
      ts_builtin_sym_end,
    ACTIONS(263), 2,
      sym_identifier,
      anon_sym_fn,
  [1511] = 2,
    ACTIONS(265), 1,
      ts_builtin_sym_end,
    ACTIONS(267), 2,
      sym_identifier,
      anon_sym_fn,
  [1519] = 2,
    ACTIONS(269), 1,
      ts_builtin_sym_end,
    ACTIONS(271), 2,
      sym_identifier,
      anon_sym_fn,
  [1527] = 2,
    ACTIONS(273), 1,
      ts_builtin_sym_end,
    ACTIONS(275), 2,
      sym_identifier,
      anon_sym_fn,
  [1535] = 2,
    ACTIONS(277), 1,
      ts_builtin_sym_end,
    ACTIONS(279), 2,
      sym_identifier,
      anon_sym_fn,
  [1543] = 1,
    ACTIONS(195), 3,
      sym_identifier,
      anon_sym_COMMA,
      anon_sym_DASH_GT,
  [1549] = 1,
    ACTIONS(207), 3,
      sym_identifier,
      anon_sym_COMMA,
      anon_sym_DASH_GT,
  [1555] = 1,
    ACTIONS(213), 3,
      sym_identifier,
      anon_sym_COMMA,
      anon_sym_DASH_GT,
  [1561] = 2,
    ACTIONS(281), 1,
      ts_builtin_sym_end,
    ACTIONS(283), 2,
      sym_identifier,
      anon_sym_fn,
  [1569] = 1,
    ACTIONS(217), 3,
      sym_identifier,
      anon_sym_COMMA,
      anon_sym_DASH_GT,
  [1575] = 2,
    ACTIONS(285), 1,
      ts_builtin_sym_end,
    ACTIONS(287), 2,
      sym_identifier,
      anon_sym_fn,
  [1583] = 2,
    ACTIONS(219), 1,
      anon_sym_DASH_GT,
    ACTIONS(187), 2,
      sym_identifier,
      anon_sym_COMMA,
  [1591] = 2,
    ACTIONS(289), 1,
      anon_sym_DASH_GT,
    ACTIONS(291), 1,
      anon_sym_do,
  [1598] = 2,
    ACTIONS(293), 1,
      anon_sym_COLON,
    ACTIONS(295), 1,
      anon_sym_EQ,
  [1605] = 2,
    ACTIONS(297), 1,
      anon_sym_DASH_GT,
    ACTIONS(299), 1,
      anon_sym_do,
  [1612] = 2,
    ACTIONS(301), 1,
      anon_sym_COLON,
    ACTIONS(303), 1,
      anon_sym_EQ,
  [1619] = 2,
    ACTIONS(305), 1,
      anon_sym_DASH_GT,
    ACTIONS(307), 1,
      anon_sym_do,
  [1626] = 2,
    ACTIONS(309), 1,
      anon_sym_DASH_GT,
    ACTIONS(311), 1,
      anon_sym_do,
  [1633] = 1,
    ACTIONS(245), 1,
      anon_sym_end,
  [1637] = 1,
    ACTIONS(261), 1,
      anon_sym_end,
  [1641] = 1,
    ACTIONS(313), 1,
      anon_sym_COLON,
  [1645] = 1,
    ACTIONS(315), 1,
      anon_sym_end,
  [1649] = 1,
    ACTIONS(229), 1,
      anon_sym_end,
  [1653] = 1,
    ACTIONS(317), 1,
      anon_sym_DASH_GT,
  [1657] = 1,
    ACTIONS(319), 1,
      anon_sym_DASH_GT,
  [1661] = 1,
    ACTIONS(269), 1,
      anon_sym_end,
  [1665] = 1,
    ACTIONS(273), 1,
      anon_sym_end,
  [1669] = 1,
    ACTIONS(277), 1,
      anon_sym_end,
  [1673] = 1,
    ACTIONS(241), 1,
      anon_sym_end,
  [1677] = 1,
    ACTIONS(321), 1,
      anon_sym_DASH_GT,
  [1681] = 1,
    ACTIONS(323), 1,
      anon_sym_DASH_GT,
  [1685] = 1,
    ACTIONS(257), 1,
      anon_sym_end,
  [1689] = 1,
    ACTIONS(325), 1,
      anon_sym_DASH_GT,
  [1693] = 1,
    ACTIONS(327), 1,
      anon_sym_DASH_GT,
  [1697] = 1,
    ACTIONS(253), 1,
      anon_sym_end,
  [1701] = 1,
    ACTIONS(237), 1,
      anon_sym_end,
  [1705] = 1,
    ACTIONS(233), 1,
      anon_sym_end,
  [1709] = 1,
    ACTIONS(285), 1,
      anon_sym_end,
  [1713] = 1,
    ACTIONS(329), 1,
      anon_sym_end,
  [1717] = 1,
    ACTIONS(281), 1,
      anon_sym_end,
  [1721] = 1,
    ACTIONS(265), 1,
      anon_sym_end,
  [1725] = 1,
    ACTIONS(249), 1,
      anon_sym_end,
  [1729] = 1,
    ACTIONS(331), 1,
      ts_builtin_sym_end,
  [1733] = 1,
    ACTIONS(333), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 32,
  [SMALL_STATE(4)] = 64,
  [SMALL_STATE(5)] = 96,
  [SMALL_STATE(6)] = 128,
  [SMALL_STATE(7)] = 160,
  [SMALL_STATE(8)] = 192,
  [SMALL_STATE(9)] = 224,
  [SMALL_STATE(10)] = 256,
  [SMALL_STATE(11)] = 282,
  [SMALL_STATE(12)] = 308,
  [SMALL_STATE(13)] = 328,
  [SMALL_STATE(14)] = 348,
  [SMALL_STATE(15)] = 368,
  [SMALL_STATE(16)] = 388,
  [SMALL_STATE(17)] = 408,
  [SMALL_STATE(18)] = 428,
  [SMALL_STATE(19)] = 448,
  [SMALL_STATE(20)] = 468,
  [SMALL_STATE(21)] = 488,
  [SMALL_STATE(22)] = 508,
  [SMALL_STATE(23)] = 528,
  [SMALL_STATE(24)] = 548,
  [SMALL_STATE(25)] = 568,
  [SMALL_STATE(26)] = 588,
  [SMALL_STATE(27)] = 608,
  [SMALL_STATE(28)] = 628,
  [SMALL_STATE(29)] = 648,
  [SMALL_STATE(30)] = 668,
  [SMALL_STATE(31)] = 688,
  [SMALL_STATE(32)] = 708,
  [SMALL_STATE(33)] = 728,
  [SMALL_STATE(34)] = 748,
  [SMALL_STATE(35)] = 767,
  [SMALL_STATE(36)] = 786,
  [SMALL_STATE(37)] = 803,
  [SMALL_STATE(38)] = 820,
  [SMALL_STATE(39)] = 837,
  [SMALL_STATE(40)] = 854,
  [SMALL_STATE(41)] = 871,
  [SMALL_STATE(42)] = 888,
  [SMALL_STATE(43)] = 905,
  [SMALL_STATE(44)] = 922,
  [SMALL_STATE(45)] = 939,
  [SMALL_STATE(46)] = 956,
  [SMALL_STATE(47)] = 973,
  [SMALL_STATE(48)] = 990,
  [SMALL_STATE(49)] = 1007,
  [SMALL_STATE(50)] = 1024,
  [SMALL_STATE(51)] = 1041,
  [SMALL_STATE(52)] = 1058,
  [SMALL_STATE(53)] = 1080,
  [SMALL_STATE(54)] = 1102,
  [SMALL_STATE(55)] = 1124,
  [SMALL_STATE(56)] = 1146,
  [SMALL_STATE(57)] = 1165,
  [SMALL_STATE(58)] = 1184,
  [SMALL_STATE(59)] = 1203,
  [SMALL_STATE(60)] = 1222,
  [SMALL_STATE(61)] = 1241,
  [SMALL_STATE(62)] = 1260,
  [SMALL_STATE(63)] = 1272,
  [SMALL_STATE(64)] = 1285,
  [SMALL_STATE(65)] = 1294,
  [SMALL_STATE(66)] = 1303,
  [SMALL_STATE(67)] = 1312,
  [SMALL_STATE(68)] = 1325,
  [SMALL_STATE(69)] = 1334,
  [SMALL_STATE(70)] = 1347,
  [SMALL_STATE(71)] = 1356,
  [SMALL_STATE(72)] = 1365,
  [SMALL_STATE(73)] = 1374,
  [SMALL_STATE(74)] = 1387,
  [SMALL_STATE(75)] = 1396,
  [SMALL_STATE(76)] = 1405,
  [SMALL_STATE(77)] = 1414,
  [SMALL_STATE(78)] = 1425,
  [SMALL_STATE(79)] = 1431,
  [SMALL_STATE(80)] = 1439,
  [SMALL_STATE(81)] = 1447,
  [SMALL_STATE(82)] = 1455,
  [SMALL_STATE(83)] = 1463,
  [SMALL_STATE(84)] = 1471,
  [SMALL_STATE(85)] = 1479,
  [SMALL_STATE(86)] = 1487,
  [SMALL_STATE(87)] = 1495,
  [SMALL_STATE(88)] = 1503,
  [SMALL_STATE(89)] = 1511,
  [SMALL_STATE(90)] = 1519,
  [SMALL_STATE(91)] = 1527,
  [SMALL_STATE(92)] = 1535,
  [SMALL_STATE(93)] = 1543,
  [SMALL_STATE(94)] = 1549,
  [SMALL_STATE(95)] = 1555,
  [SMALL_STATE(96)] = 1561,
  [SMALL_STATE(97)] = 1569,
  [SMALL_STATE(98)] = 1575,
  [SMALL_STATE(99)] = 1583,
  [SMALL_STATE(100)] = 1591,
  [SMALL_STATE(101)] = 1598,
  [SMALL_STATE(102)] = 1605,
  [SMALL_STATE(103)] = 1612,
  [SMALL_STATE(104)] = 1619,
  [SMALL_STATE(105)] = 1626,
  [SMALL_STATE(106)] = 1633,
  [SMALL_STATE(107)] = 1637,
  [SMALL_STATE(108)] = 1641,
  [SMALL_STATE(109)] = 1645,
  [SMALL_STATE(110)] = 1649,
  [SMALL_STATE(111)] = 1653,
  [SMALL_STATE(112)] = 1657,
  [SMALL_STATE(113)] = 1661,
  [SMALL_STATE(114)] = 1665,
  [SMALL_STATE(115)] = 1669,
  [SMALL_STATE(116)] = 1673,
  [SMALL_STATE(117)] = 1677,
  [SMALL_STATE(118)] = 1681,
  [SMALL_STATE(119)] = 1685,
  [SMALL_STATE(120)] = 1689,
  [SMALL_STATE(121)] = 1693,
  [SMALL_STATE(122)] = 1697,
  [SMALL_STATE(123)] = 1701,
  [SMALL_STATE(124)] = 1705,
  [SMALL_STATE(125)] = 1709,
  [SMALL_STATE(126)] = 1713,
  [SMALL_STATE(127)] = 1717,
  [SMALL_STATE(128)] = 1721,
  [SMALL_STATE(129)] = 1725,
  [SMALL_STATE(130)] = 1729,
  [SMALL_STATE(131)] = 1733,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(127),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(122),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(128),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(125),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [133] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(108),
  [136] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(52),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(131),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 1, .production_id = 1),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 1, .production_id = 1),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_parameters_repeat1, 1),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 1),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameters, 2),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 3, .production_id = 4),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, .production_id = 4),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_t_fn, 4, .production_id = 10),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_t_fn, 4, .production_id = 10),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_t_pu, 4, .production_id = 10),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_t_pu, 4, .production_id = 10),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_t_fn, 3, .production_id = 7),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_t_fn, 3, .production_id = 7),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_t_pu, 3, .production_id = 7),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_t_pu, 3, .production_id = 7),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 1),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameters, 1),
  [223] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2), SHIFT_REPEAT(66),
  [226] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2), SHIFT_REPEAT(77),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__fn_body, 2),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__fn_body, 2),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 5, .production_id = 9),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 5, .production_id = 9),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pu, 3, .production_id = 2),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pu, 3, .production_id = 2),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pu, 4, .production_id = 5),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pu, 4, .production_id = 5),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pu, 4, .production_id = 6),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pu, 4, .production_id = 6),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 3, .production_id = 2),
  [251] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 3, .production_id = 2),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 1),
  [255] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 1),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1),
  [259] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_declaration, 4, .production_id = 3),
  [263] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_const_declaration, 4, .production_id = 3),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mut_declaration, 4, .production_id = 3),
  [267] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mut_declaration, 4, .production_id = 3),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 4, .production_id = 5),
  [271] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 4, .production_id = 5),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pu, 5, .production_id = 9),
  [275] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pu, 5, .production_id = 9),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 4, .production_id = 6),
  [279] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 4, .production_id = 6),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_declaration, 5, .production_id = 8),
  [283] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_const_declaration, 5, .production_id = 8),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mut_declaration, 5, .production_id = 8),
  [287] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mut_declaration, 5, .production_id = 8),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [331] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_sylt(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
